### ISSUE TITLE
custom-functions-metadata-plugin: doesn't work with clean-webpack-plugin@3.0.0

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/Office-Addin-Scripts#143]
For the https://github.com/OfficeDev/Excel-Custom-Functions project, if the version of clean-webpack-plugin is updated to version 3.0.0 in package.json

```
"clean-webpack-plugin": "^3.0.0",
```

and the import is updated as in https://github.com/OfficeDev/Excel-Custom-Functions/commit/e02646a8ffcccf3412a3be62ccf26c3269dd08ba,

"npm run build" will not build successfully.

**Comment by hyacinthus** [comment]
1 year past...

**Comment by akrantz** [comment]
The change in [v3.0.0](https://github.com/johnagan/clean-webpack-plugin/releases/tag/v3.0.0) to use emit hook seems to interfere with custom-functions-metadata-plugin.

```
c:\dev\git\Excel-Custom-Functions>npm run build

> excel-custom-functions@2.0.0 build c:\dev\git\Excel-Custom-Functions
> webpack -p --mode production --https false

c:\dev\git\Excel-Custom-Functions\dist\functions.json created for file: c:\dev\git\Excel-Custom-Functions\src\functions\functions.ts
Error: ENOENT: no such file or directory, stat 'c:\dev\git\Excel-Custom-Functions\dist\functions.json'
    at Object.statSync (fs.js:1009:3)
    at c:\dev\git\Excel-Custom-Functions\node_modules\custom-functions-metadata-plugin\lib\customfunctionsplugin.js:46:34
 
```
So far, we've just stayed using the older version.

**Comment by hyacinthus** [comment]
I just ignored it:
```javascript
            new CleanWebpackPlugin({
                cleanOnceBeforeBuildPatterns: dev ? [] : ["**/*", "!functions.json"]
            })
```

**Comment by akrantz** [comment]
That's a reasonable workaround.  @TCourtneyOwen you could make this change.

**Comment by TCourtneyOwen** [comment]
I will try and make the change today

**Comment by TCourtneyOwen** [comment]
@akrantz just to clarify, this change needs to happen in the Custom Functions project template, right?

**Comment by igor-ribeiiro** [comment]
The Custome Functions templates are right now using version 3.0.0 of the `clean-webpack-plugin` with no build errors, so I will be closing this issue.
Feel free to reopen if the problem still exists.
