### ISSUE TITLE
office-addin-dev-certs: make it work on Windows 7

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/Office-Addin-Scripts#151]
See https://github.com/OfficeDev/Excel-Custom-Functions/issues/168

**Comment by asachin96** [comment]
Fixed in https://github.com/OfficeDev/Office-Addin-Scripts/pull/153

**Comment by darichey** [comment]
Is the fix targeted to a release? This is a blocking issue for me at the moment.

**Comment by akrantz** [comment]
We're working to fix some issues. It will be released soon.

You could build and run this locally to be unblocked
