### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by GabeMedrash** [OfficeDev/Office-Addin-Scripts#155]
I attempted to run the [Add-in generator](https://github.com/OfficeDev/generator-office) on Linux, but I hit an exception from `office-addin-dev-certs` that the `linux` platform is not supported. Is making this compatible with Linux as easy as updating the `getInstallCommand`, `getUninstallCommand`, and `getVerifyCommand` functions with a case for `linux`? If so, I'd be happy to submit a PR.

**Comment by akrantz** [comment]
It should be. We would happily accept a PR if you can get it working.

**Comment by GabeMedrash** [comment]
Submitted! https://github.com/OfficeDev/Office-Addin-Scripts/pull/156

**Comment by KelBowen** [comment]
@TCourtneyOwen - I notice the PR is still open. Should we review and merge? Or how to resolve this request?

**Comment by LouMM** [comment]
@igor-ribeiiro to confirm functionality.

**Comment by igor-ribeiiro** [comment]
This should be fixed in https://github.com/OfficeDev/Office-Addin-Scripts/pull/426
Please, reopen this issue if it is not the case
