### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [OfficeDev/Office-Addin-Scripts#157]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/OfficeDev/Office-Addin-Scripts/search?q=0.1-security&unscoped_q=0.1-security

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by akrantz** [comment]
Thanks for letting us know!
