### ISSUE TITLE
'office-addin-manifest modify' does not preserve comments in the manifest

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/Office-Addin-Scripts#20]
This is because xml2js does not preserve comments. https://github.com/Leonidas-from-XIV/node-xml2js/pull/44

**Comment by millerds** [comment]
There doesn't seem to be any movement on the xml2js library to add support for comments in years.  I also haven't seen any customer feedback asking for this.  Since manifests are moving to a json format anyway it doesn't seem work keeping this around.
