### ISSUE TITLE
Excel: Add-in "manifest.xml" file with invalid version still passes validation when using the Excel-Custom-Functions repo's validation command

### ISSUE THREAD

**Issue by dzwillia** [OfficeDev/Office-Addin-Scripts#207]
## Expected Behavior
According to the docs (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/version), the manifest file requires the version to be structure with 4 numbers (`<Version>n .n .n .n</Version>`). Manifest validation should pass when the version follows (e.g. `1.0.0.0`) and should fail when it does not (e.g. `1.0.0`).

## Current Behavior
Starting with a valid manifest file, change the version to something that only has 3 numbers in it (e.g. `1.0.0`). Attempt to validate this manifest file again. Validation still passes. This is very problematic for debugging -- This version actually is accepted by Desktop Excel, but fails when trying to install the add-in with Excel in the browser. Both desktop and Excel Online should both handle the manifest in the same manner. Since this pertains specifically to the manifest being invalid, though, this could be headed off at the pass if the manifest validation simple would fail and let the user know that their version is not valid. 

## Steps to Reproduce, or Live Example
Follow the steps in this tutorial: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows

After running `yo office`, select the following options:

```
? Choose a project type: Excel Custom Functions Add-in project
? Choose a script type: JavaScript
? What do you want to name your add-in? My Office Add-in
```

1) Run `npm run validate`. Works!
2) Build the add-in with `npm run build` and then run it with `npm start`.
3) Open the add-in in Excel Desktop. Works!
4) Open the add-in in Excel Online (by uploading the manifest.xml file). Works!

Now, edit the manifest.xml file and change the version from `<Version>1.0.0.0</Version>` to `<Version>1.0.0</Version>`. Run `npm stop` and then follow the exact same steps above.

1) Run `npm run validate`. Works! (even though it should error out because the version in invalid according to the manifest.xml docs (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/version)
2) Build the add-in with `npm run build` and then run it with `npm start`.
3) Open the add-in in Excel Desktop. Works!
4) Open the add-in in Excel Online (by uploading the manifest.xml file). Fails. This is the error message that loads right away after uploading the manifest file:

![excel-online-add-in-error](https://user-images.githubusercontent.com/1385356/63824613-c3f38480-c925-11e9-9afc-24b2a7c44162.png)

## Context

This issue actually me about a day's worth of work as I thought there was actually an issue with my custom function. Since the error message attached is shown before any code is called, there is no way to debug what is going on. If the error messages were a bit more clear and stated that there was an error in the manifest file (or even better -- *WHAT* is wrong in the manifest file), that would probably go a long way to making this a better experience.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop & Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number:
    > Microsoft Excel for Office 365 MSO (16.0.12022.20000) 64-bit
    > Version 1902 (Build 12022.20000 Click-to Run)
    > Office Insider
* Operating System: Windows 10
* Browser (if using Office Online):
    > Google Chrome | 76.0.3809.100 (Official Build) (64-bit) (cohort: Stable)
    > Revision: ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
    > OS: Windows 10 OS Version 1903 (Build 18362.295)

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by akrantz** [comment]
@kbrandl The issue is with the validation service which is called. We'll need to file an internal bug about the issue.

**Comment by kbrandl** [comment]
@akrantz thanks for the clarification. Will you be doing that (filing the internal bug)?

**Comment by TCourtneyOwen** [comment]
Opened internal bug https://office.visualstudio.com/DefaultCollection/OC/_workitems/edit/4354188
