### ISSUE TITLE
Office-Addins & Blazor: Possible?

### ISSUE THREAD

**Issue by mclean25** [OfficeDev/Office-Addin-Scripts#209]
Is it possible to combine Blazor and Office Addins? Would like to be able to execute .NET standard libraries from the task pane.

My apologies if this is already listed somewhere, I've been able to find anything in searches.

**Comment by LouMM** [comment]
Thank you for your suggestion, this is a good one @mclean25! We are looking into this support. If you want to enter a UserVoice for this suggestion, the community can also vote on it. Cheers!
