### ISSUE TITLE
Unable to delete registry value 

### ISSUE THREAD

**Issue by hakachouti** [OfficeDev/Office-Addin-Scripts#215]
Hi,

I created a started app with Yeoman using office-addin-taskpane-react@0.0.1
Here is the console output:

`npm start desktop                                      
> office-addin-taskpane-react@0.0.1 start C:\Users\xxx\excel-addin
> office-addin-debugging start manifest.xml "desktop"

Debugging is being started...
App type: desktop
Enabled debugging for add-in 05c2e1c9-3e1d-406e-9a91-e9ac64854143. Debug method: 0
Starting the dev server... (webpack-dev-server --mode development)
The dev server is running on port 3000. Process id: 22816
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Unable to delete registry value "C:\Users\xxx\excel-addin\manifest.xml" in key "HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer".
ProcessUncleanExitError: DELETE command exited with code 1:

Erreur�: Erreur�: le syst�me n'a pas trouv� la cl� ou la valeur de Registre sp�cifi�e.`

This error is preventing the debugging from starting. After digging aroud a bit, I think issue lies with the RegistryKey class. The deleteValue function (line 112) is matching the error message to a specific string in english, but my system is returning an error message in french.

If I create the value it is looking for in the registry before starting the debugger I do not have an issue.

**Comment by akrantz** [comment]
Thanks for providing the information that this was related to the language of the error message.

I've made a pull request to fix this: https://github.com/OfficeDev/Office-Addin-Scripts/pull/216

**Comment by akrantz** [comment]
The fix has been published to office-addin-dev-settings@next so if you use "npm install -D office-addin-dev-settings@next" to get the latest version, you should be able to confirm that it has fixed this issue.
