### ISSUE TITLE
Unable to Specify Template Document

### ISSUE THREAD

**Issue by bbrougher-cerium** [OfficeDev/Office-Addin-Scripts#220]
In visual studio we have the option to specify a template file that our sideloaded app starts with. With this, the template is hard coded. A flag or environment variable to change this would be awesome.

**Comment by CarlVerret** [comment]
totally agree with that !  Debugging or testing the add-in with a predetermined document would be really usefull

**Comment by LouMM** [comment]
@bbrougher-cerium This is a great suggestion! Just to confirm your ask, you would like to be able to specify the document URL that you want to load, and sideload the addon, into. Is that correct?

**Comment by moutansos** [comment]
@LouMM Yes that would be great, it would also be useful to be able to point to a local template file as well (probably only would work for the desktop version of office). Right now I have to go replace the document in the node_modules\office-addin-dev-settings\templates via a PowerShell script which I'm sure is an extremely unsupported way of going about it.

**Comment by millerds** [comment]
Looks like this was already done via https://github.com/OfficeDev/Office-Addin-Scripts/commit/43f7d7458d9b2e17ec38dbe43db0a2262d494a90.  It should work in current version of the office-addin-dev-settings package.

Note that it assumes the specified document has the test add-in reference already.
