### ISSUE TITLE
Can't start dev server in other port than 3000

### ISSUE THREAD

**Issue by guillermoparral1995** [OfficeDev/Office-Addin-Scripts#228]
I'm currently developing an Excel add-in in Windows 10. Since I'm trying to open two instances of the add-in in different ports, I'm trying to start another dev-server in port 44389 by doing 
```
office-addin-debugging start manifest.xml desktop --dev-server-port 44389
``` 
but the following output shows up: 
```
Debugging is being started...
App type: desktop
Enabled debugging for add-in 20c008db-10d8-4e87-bed4-29aaa26f673b. Debug method: 0
Starting the dev server... (webpack-dev-server --mode development)
Unable to start the dev server. Error: The dev server is not running on port 44389.
Sideloading the Office Add-in...
Debugging started.
```

If I run the application with the default port (3000), it works ok.

**Comment by akrantz** [comment]
The problem is that you’ve changed the port for the debugging settings, but haven’t told webpack-dev-server to run on the different port.

Instead of adding the –dev-server-port parameter, go to package.json and in the config section, change the value of “dev-server-port”

  "config": {
    "dev-server-port": 44389
  },

The webpack config will pick up this value:

    devServer: {
      port: process.env.npm_package_config_dev_server_port || 3000
    }

The office-addin-debugging start command also will use this same value.

Adam

**Comment by guillermoparral1995** [comment]
Thanks for the tip! But what if I want to run two of them in parallel, one in 3000 and the other one in 44389? Is there any way to do something like that?

**Comment by akrantz** [comment]
Why/how would you have two instances of the same add-in from the same code base? I was thinking you had two separate add-ins running inside office at one time. Usually, this would come from two separate code bases each with their own dev server instance.

**Comment by guillermoparral1995** [comment]
I have a server listening for two different ports, and my add-in sends a message to said server, and then listens for a response. I want to have two instances, each running in a different port so the response sent from the server can be heard from the add-in and then have the add-in do something according to that response. All of this is accomplished by WebSockets and the main goal is to have a Google Sheets kind of behaviour through this communication, which can't be accomplished if both instances run in the same port

**Comment by akrantz** [comment]
Well I'm not a websocket expert, but wouldn't you only need one webpack-dev-server instance, and create two separate websockets off of that?

**Comment by guillermoparral1995** [comment]
You were right, there wasn't any need for two instances. Thanks for all the help! I'll close this issue

**Comment by akrantz** [comment]
Im glad you were able to resolve this!
