### ISSUE TITLE
office-addin-dev-certs: keeps adding new certs on mac

### ISSUE THREAD

**Issue by gordonmleigh** [OfficeDev/Office-Addin-Scripts#233]
When the certificate has less than a day until expiry, the certificate verification step fails, and it adds a new certificate. The next time it tries to verify the certificate, it still sees the old certificate, and creates another new certificate.

This is how you are verifying certificates:

https://github.com/OfficeDev/Office-Addin-Scripts/blob/8b856472b64a626a883e9031f5624f9ee68fdf3b/packages/office-addin-dev-certs/src/verify.ts#L15-L16

The `security find-certificate` call finds the first matching certificate, which is the expiring one, even after a new certificate is added.

**Comment by millerds** [comment]
I have checked in some updates to scripts that manage the certs.  They should be better about deleting expired and duplicate certs and looking for a valid one.
