### ISSUE TITLE
npm task issues

### ISSUE THREAD

**Issue by jjr2527** [OfficeDev/Office-Addin-Scripts#239]
All of the tasks are failing for me.  I'm wondering if it's my scenario and it's an edge case.  

PS Z:\jason_r On My Mac\source\ToucanOfficeAddIn> npm run start

> office-addin-taskpane-js@0.0.1 start Z:\jason_r On My Mac\source\ToucanOfficeAddIn
> office-addin-debugging start manifest.xml

npm : 'office-addin-debugging' is not recognized as an internal or external command,
At line:1 char:1
+ npm run start
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('office-addin-d...ternal command,:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.

Even though I have done an npm install with no errors the tools are still being seen as unknown commands.  

I am running a VM instance of Windows on a mac, and I am running the project from a shared drive from the host.

**Comment by jjr2527** [comment]
After pulling the repo down to a folder on the c: drive of the VM and running the install over again things proceeded much further.  That said I am getting the side load unsupported error below.

```
office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in 769e871f-dbc3-4e9a-bb5e-44cfbc9ea967. Debug method: 0
Starting the dev server... (webpack-dev-server --mode development)
The dev server is running on port 3000. Process id: 7772
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Offi
```

**Comment by akrantz** [comment]
It's difficult to tell what's going on. Can you provide more of the error info for "Error: Unable to sideload"?

**Comment by akrantz** [comment]
Did you just create the add-in with Yo Office? Which Office app are you targeting?

**Comment by jjr2527** [comment]
Yes using the standard yo office walkthroughs.  I'm not sure how to get you more information about the errors as that is all that shows in the console on run.

I am targeting outlook.

**Comment by akrantz** [comment]
Outlook does not support sideload. I'm sorry that this maybe misleading in the docs. Instead of "npm start", you can use "npm run dev-server" to have it run webpack-dev-server, and then follow [these instructions](https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing) to load the add-in into Outlook.

**Comment by akrantz** [comment]
I've created a bug for the misleading documentation. https://github.com/OfficeDev/outlook-dev-docs/issues/792

**Comment by akrantz** [comment]
I've also created a bug for office-addin-debugging to handle this better: https://github.com/OfficeDev/Office-Addin-Scripts/issues/240

**Comment by akrantz** [comment]
I'm going to close this bug. If you're still having problems, please feel free to comment and/or reopen it.
