### ISSUE TITLE
Outlook does not support sideload -- tooling should handle more gracefully

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/Office-Addin-Scripts#240]
If Yo Office is used to create a project for Outlook, the "npm start" command should handle the fact that Outlook cannot sideload more gracefully. It can ensure the dev server is running, and then provide instructions for the user to sideload manually. See https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing.

**Comment by LouMM** [comment]
Approving for later milestone to add Content (docs) and for additional warning, descriptive, messages in command.

**Comment by LouMM** [comment]
Completed.
