### ISSUE TITLE
[office-addin-sso] - jquery error

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/Office-Addin-Scripts#251]
I've created an SSO-enabled Outlook add-in by using the Yeoman generator and running `npm run configure-sso` (as described in the [SSO quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart)). I'm unable to successfully run this add-in in _Outlook on the web_, due to error `$ is not defined` being thrown from `message-helper.js` in the Office Add-in SSO package.

Screenshot:

![image](https://user-images.githubusercontent.com/3019529/73296991-973ae600-41bf-11ea-8feb-7e3843e4b414.png)

**Comment by LouMM** [comment]
Engineer to look into HTML to validate if there are elements matching Jquery

**Comment by TCourtneyOwen** [comment]
This issue appears to be fixed. No longer repro in Outlook Online
