### ISSUE TITLE
Linting Error: Cannot find module '{path containing a space here}'

### ISSUE THREAD

**Issue by andreismolingmail** [OfficeDev/Office-Addin-Scripts#255]
It looks like the loader doesn't accept spaces in the path.

Part 1.

npm run lint

> office-addin-myaddin-angular@0.0.3 lint {path}\**My Outlook Add-in**
> office-addin-lint check

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '{path}\**My**'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-addin-myaddin-angular@0.0.3 lint: `office-addin-lint check`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-addin-myaddin-angular@0.0.3 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     {profile}\AppData\Roaming\npm-cache\_logs\2020-02-06T15_14_32_020Z-debug.log

Part 2. 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle office-addin-myaddin-angular@0.0.3~prelint: office-addin-myaddin-angular@0.0.3
6 info lifecycle office-addin-myaddin-angular@0.0.3~lint: office-addin-myaddin-angular@0.0.3
7 verbose lifecycle office-addin-myaddin-angular@0.0.3~lint: unsafe-perm in lifecycle true
8 verbose lifecycle office-addin-myaddin-angular@0.0.3~lint: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;{path}\My Outlook Add-in\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Borland\Delphi7\Bin;C:\Program Files (x86)\Borland\Delphi7\Projects\Bpl\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;{profile}\AppData\Local\Microsoft\WindowsApps;{profile}\AppData\Local\atom\bin;{profile}\AppData\Local\Microsoft\WindowsApps;{profile}\AppData\Roaming\npm;{profile}\AppData\Local\Programs\Microsoft VS Code\bin;{profile}\AppData\Local\GitHubDesktop\bin;{profile}\AppData\Local\Programs\Fiddler
9 verbose lifecycle office-addin-myaddin-angular@0.0.3~lint: CWD: {path}\My Outlook Add-in
10 silly lifecycle office-addin-myaddin-angular@0.0.3~lint: Args: [ '/d /s /c', 'office-addin-lint check' ]
11 silly lifecycle office-addin-myaddin-angular@0.0.3~lint: Returned: code: 1  signal: null
12 info lifecycle office-addin-myaddin-angular@0.0.3~lint: Failed to exec lint script
13 verbose stack Error: office-addin-myaddin-angular@0.0.3 lint: `office-addin-lint check`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid office-addin-myaddin-angular@0.0.3
15 verbose cwd {path}\My Outlook Add-in
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error office-addin-myaddin-angular@0.0.3 lint: `office-addin-lint check`
22 error Exit status 1
23 error Failed at the office-addin-myaddin-angular@0.0.3 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by LouMM** [comment]
Thank you @andreismolingmail for the report. We are not able to reproduce this issue. I you create a new template using Yo Office and add a space in the name, does it reproduce?

**Comment by LouMM** [comment]
Look to assigning bug for fix, issue with linter package, check code

**Comment by igor-ribeiiro** [comment]
Hi @andreismolingmail, thanks again for submitting the issue.
It has been solved in [https://github.com/OfficeDev/Office-Addin-Scripts/pull/385](https://github.com/OfficeDev/Office-Addin-Scripts/pull/385) which will be published in a few days, with this bugfix.
