### ISSUE TITLE
The latest release is broken

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/Office-Addin-Scripts#305]
# Expected behavior

The lib/ directory is present in the release packages for all scripts.

# Current behavior

Multiple packages fail upon requiring them because they try to import from the 'lib/' directory that is absent in the latest release.

Affected packages are at least office-addin-manifest@1.5.5, office-addin-usage-data@1.1.5, custom-functions-metadata@1.0.31, custom-functions-metadata-plugin@1.0.31 etc.

They are all packages that were released as part of the latest release AFAIU.

**Comment by TCourtneyOwen** [comment]
@wh1t3cAt1k  Please try out the latest versions of these packages that we published yesterday. There was an an apparent publishing problem to NPM for the package versions you cite. Unfortunately, the publishing process didn't return an error, so we didn't know there was a problem until people reported issues.

Thanks,

Courtney

**Comment by TCourtneyOwen** [comment]
This is fixed and resolved
