### ISSUE TITLE
Module not found: Error: Can't resolve 'https' in Angular app

### ISSUE THREAD

**Issue by kdubious** [OfficeDev/Office-Addin-Scripts#309]
Getting the following error in an Angular app.

ERROR in ./node_modules/office-addin-sso/lib/odata-helper.js
Module not found: Error: Can't resolve 'https' in '***\node_modules\office-addin-sso\lib'

I think it is due to the fact that Angular no longer assumes Node modules are available.

**Comment by LouMM** [comment]
Thank you @kdubious !  We may need some assistance on this one. Are there Angular experts that can assist us with the latest Angular updates?

**Comment by millerds** [comment]
If there is any further questions on this please re-open
