### ISSUE TITLE
eslint-config-office-addins 1.0.16 is missing the lib folder

### ISSUE THREAD

**Issue by 0m4r** [OfficeDev/Office-Addin-Scripts#323]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
by running "npm install eslint-config-office-addins" the latest version of the npm module is installed and works
**(all seems to work with version eslint-config-office-addins@1.0.15)**

# Current behavior
after I run the lint comment via the "npm run lint" command I get this:

> > enerlytics-excel-addin-vue@0.1.0 lint:office [EDITED_PATH] office-addin-lint check
> 
> 
> Oops! Something went wrong! :(
> 
> ESLint: 6.8.0.
> 
> ESLint couldn't find the config "eslint-config-office-addins" to extend from. Please check that the name of the config is correct.
> 
> The config "eslint-config-office-addins" was referenced from the config file in "[EDITED_PATH]/.eslintrc.json".
> 
> If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.

## Steps to Reproduce

follow the instruction in the README.md of this repo: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-lint/README.md

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: OSX Catalina (10.15.6)
* Node version: v10.17.0
* Office version: not relevant
* Tool version: eslint-config-office-addins 1.0.16

**Comment by hyacinthus** [comment]
eslint-plugin-office-addins 0.1.7 have this issue too.

0.1.6 is ok.

**Comment by TCourtneyOwen** [comment]
@hyacinthus Please try 1.0.19. This should fix the issue, Please let us know if that's not the case.

Thanks,

Courtney

**Comment by hyacinthus** [comment]
@TCourtneyOwen  my project is start from react demo. It do not use eslint-config-office-addins. but use eslint-plugin-office-addins . I'm not see a new version for this package.

**Comment by LoveSponge** [comment]
@TCourtneyOwen still borked, see #333.

**Comment by TCourtneyOwen** [comment]
Can you please update to v.1.0.19.  It's the latest version.

Thanks,

Courtney

**Comment by LoveSponge** [comment]
@TCourneyOwen

Check npm. See my comment on #333 

Latest version for config is as you say but latest version for plugin is v0.1.7.

**Comment by TCourtneyOwen** [comment]
I just published eslint-plugin-office-addins@0.1.10.  Please try that out

Thanks,

Courtney
