### ISSUE TITLE
Unable to start the dev server. Error: The dev server is not running on port 3000.

### ISSUE THREAD

**Issue by sjgarland** [OfficeDev/Office-Addin-Scripts#330]
Last spring, I created an add-in for Excel using the Yeoman Office Generator configured for Angular/TypeScript and Visual Studio Code running under Windows 10.  This add-in worked back then with all versions of Excel, but fails now with Excel for the Web when run under Internet Explorer.  It still works with other versions of Excel, but Internet Explorer can no longer load taskpane.js.

For comparison, I generated a new, smaller add-in using Yeoman.  This new add-in works with all versions of Excel.  The main differences between the new and old add-in are in package.json.  When I use the new package.json with the old add-in, I get the error message "Unable to start the dev server. Error: The dev server is not running on port 3000."

I have tried all remedies for starting a dev server suggested in an earlier thread on this issue: verifying certificates, restarting Windows (to ensure that nothing else is running on port 3000), and running `npm outdated --long` (which showed that everything was up-to-date except for Angular, which was running version 5.2.11 instead of 10.1.5 and did not cause a problem with the new add-in).

**Comment by akrantz** [comment]
Does `npm run dev-server` start webpack-dev-server running on `https://localhost:3000`?  It seems to imply that it doesn't see it running.

You should be able to open a browser to that, or the url to the HTML file specified in the SourceLocation in the manifest, e.g. `https://localhost:3000/taskpane.html`

You should see a lock icon in the browser to show if you have a valid SSL cert for localhost.  We've integrated validating and creating this cert in the webpack config, but you could miss the dialog prompt which can appear to ask for permission to install the cert.

You can use `netstat -ano | findstr :3000` to scan for what processes are using port 3000. You can change the number. For ports in use, the last number on the line is the process id, which can help identify processes to kill if something was still using port 3000. I don't think this is your problem though because it is not detecting that something is running on port 3000.

**Comment by sjgarland** [comment]
'npm run dev-server’ does not start web pack-dev-server.  It results in the following error:

PS C:\Users\Stephen Garland\Documents\XLray> npm run dev-server

> yo-office@0.0.1 dev-server C:\Users\Stephen Garland\Documents\XLray
> webpack-dev-server --mode development

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- C:\Users\Stephen Garland\Documents\XLray\node_modules\webpack-dev-server\bin\webpack-dev-server.js

I re-ran ’npm install’ after deleting the node_modules directory and package-lock.json, but that didn’t help.  There is no module 'webpack-cli/bin/config-yargs’ in the latest release 4.0.0 of webpack-cli.  In release 3.3.12 of webpack-cli, there was a file 'webpack-cli/bin/config/config-yargs.js’, but that file does not exist in release 4.0.0.

Is there something wrong with release 4.0.0 of webpack-cli, or am I doing something wrong?

For reference, here are the contents of package.json.

{
  "name": "xl-ray",
  "version": "0.0.1",
  "license": "MIT",
  "config": {
    "app-to-debug": "excel",
    "app-type-to-debug": "desktop",
    "dev-server-port": 3000
  },
  "scripts": {
    "build": "webpack -p --mode production --https false",
    "build:dev": "webpack --mode development --https false",
    "build-dev": "webpack --mode development --https false && echo . && echo . && echo . && echo Please use 'build:dev' instead of 'build-dev'.",
    "dev-server": "webpack-dev-server --mode development",
    "lint": "office-addin-lint check",
    "lint:fix": "office-addin-lint fix",
    "prettier": "office-addin-lint prettier",
    "start": "office-addin-debugging start manifest.xml",
    "start:desktop": "office-addin-debugging start manifest.xml desktop",
    "start:web": "office-addin-debugging start manifest.xml web",
    "stop": "office-addin-debugging stop manifest.xml",
    "validate": "office-addin-manifest validate manifest.xml",
    "watch": "webpack --mode development --watch"
  },
  "dependencies": {
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@microsoft/office-js-helpers": "^1.0.1",
    "office-ui-fabric-js": "^1.3.0",
    "rxjs": "^6.5.4",
    "zone.js": "^0.11.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "@babel/polyfill": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@types/find-process": "1.2.0",
    "@types/office-js": "^1.0.108",
    "@types/office-runtime": "^1.0.14",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^6.0.3",
    "eslint-config-office-addins": "^1.0.15",
    "file-loader": "^6.1.1",
    "find-process": "^1.4.3",
    "html-loader": "^1.3.2",
    "html-webpack-plugin": "^4.3.0",
    "office-addin-cli": "^1.0.10",
    "office-addin-debugging": "^3.0.37",
    "office-addin-dev-certs": "^1.5.7",
    "office-addin-lint": "^1.0.23",
    "office-addin-manifest": "1.5.9",
    "office-addin-prettier-config": "^1.0.12",
    "source-map-loader": "^1.1.1",
    "ts-loader": "^8.0.5",
    "typescript": "^4.0.3",
    "webpack": "^5.1.0",
    "webpack-cli": "^4.0.0",
    "webpack-dev-server": "^3.11.0"
  },
  "prettier": "office-addin-prettier-config"
}

**Comment by TCourtneyOwen** [comment]
Do you in fact see webpack-cli under node_modules in your project?

**Comment by sjgarland** [comment]
Yes, I see it there.  Its CHANGELOG.md says that it is version 6.1.0, even though my package.json specifies version ^4.0.0.

**Comment by JensMadsen** [comment]
I have been troubled by this issue for more than a day now.... I get my add-in up and running again (sideload Word Desktop on Windows; works perfectly for word online etc) by downgrading webpack-cli from 4.1.0 to 3.3.9.

**Comment by LouMM** [comment]
Can't reproduce the issue. Please re-open if you are still having a problem. Thank you for submitting.
