### ISSUE TITLE
Manifests targeting ExcelApi > 1.1 still attempt to support Excel for Mac 2016

### ISSUE THREAD

**Issue by chucklay** [OfficeDev/Office-Addin-Scripts#332]
When defining `Requirements` in a manifest, the supported platforms are automatically determined. However, it seems like Office for Mac 2016 seems to always be considered a supported platform, even when API requirement sets that it does not support are specified

## Expected Behavior

With the following `Requirements` section in a manifest, Excel for Mac 2016 should not be considered a supported platform (It only supports ExcelApi 1.1, and does not appear to support the CustomFunctionsApi at all, judging by this page: https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability)

```
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
      <Set Name="ExcelApi" MinVersion="1.8"/>
    </Sets>
  </Requirements>
```

## Current Behavior

With the above-mentioned `Requirements` section, `npm run validate` spits out the following supported platforms:
```
Based on the requirements specified in your manifest, your add-in can run on the following platforms; your add-in will be tested on these platforms when you submit it to the Office Store:
  - Excel 2016 or later on Mac
  - Excel 2016 or later on Windows
  - Excel on the web
```

The manifest upload section on the partner center's dashboard also lists these as supported platforms.

## Steps to Reproduce, or Live Example

Gist of our current manifest: https://gist.github.com/chucklay/025b4fe4482f69f364a9f4f3c898f84e

* Additional details:
This should NOT support Office for Mac 2016 but `npm run validate` and the partner center suggest that it DOES.

## Context

**This is a blocker issue that is preventing us from distributing our add-in, as it fails validation testing when it's run on Excel for Mac 2016.**

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
N/A - this is a problem with the submission/manifest impacting compatibility.

**Comment by jeremy-msft** [comment]
Thank you for your report. We’ve investigated and this appears to be a known issue with our version strings. Internally, we will validate against the latest monthly channel version on Mac, but currently due to an issue the version in the validation report says “Excel 2016”.  For your particular case, custom functions are not supported in the one-time purchase versions of Excel or Excel 2016.  If you have any more issues with regards to submission, you can raise a support ticket here: https://aka.ms/marketplacepublishersupport

**Comment by chucklay** [comment]
Hi @jeremy-msft , thanks for the update.

Would you be able to clarify something for me? If I specify in my the Requirements section of the manifest that my add-in requires the CustomFunctionsRuntime, as well as ExcelApi >= 1.8, my add-in shouldn't be tested on (or made available to) platforms that don't support those APIs, correct? 

When we got our latest certification report back, the main validation failure was:

```
1100.4.4.5 Office for Mac

Your offer is not working in Office 2016 for Mac on macOS: Catalina 10.15.4 using Office version 16.41.

The add-in displays an error when inserting Custom function: {one of the custom functions we have}
```

From my understanding, that version of office does not support custom functions at all (which, again, isn't a problem for us). I just want to make sure that this is an error on the part of the testers, or if there's something else we need to do to indicate that our add-in shouldn't be tested on/made available to that platform. I can live with the validation report being slightly off, but if the certification team is testing against the wrong version, that's a little bit more of a problem ;)

**Comment by jeremy-msft** [comment]
Hi @chucklay, version 16.41 is last month's [release](https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac) of Office for Mac and [supports](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-requirement-sets) the latest custom functions requirement set, so your custom functions should work in that configuration.  If you're unable to repro the same issue, I'd suggest opening a support ticket using my earlier link.
