### ISSUE TITLE
eslint-plugin-office-addins not found by eslint

### ISSUE THREAD

**Issue by LoveSponge** [OfficeDev/Office-Addin-Scripts#333]
#Expected behavior

Following the tutorial [here](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) should give all the necessary dependencies to run eslint.

# Current behavior

Running `eslint` after `npm install`-ing produces the below error (see **failure logs** below)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. follow the tutorial at [here](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
2. After `npm install` run `eslint --print-config .eslintrc.json`

## Context

* Node version: v14.12.0
* ESLint version: v7.12.1
* office-addin-lint: 1.0.27
* eslint-config-office-addins: 1.0.19
* eslint-plugin-office-addins: 0.1.7

```json
.eslint.json
{
  "parser": "@typescript-eslint/parser",
  "plugins": [
    "react",
    "@typescript-eslint",
    "office-addins"
  ],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    },
    "project": "./tsconfig.json"
  },
  "extends": [
    "plugin:office-addins/react"
  ],
  "settings": {
    "react": {
      "version": "detect"
    }
  }
}
```

## Failure Logs

```
[lovesponge@lovesponge outlookAddin]$ eslint --print-config .eslintrc.json 

Oops! Something went wrong! :(

ESLint: 7.12.1

ESLint couldn't find the plugin "eslint-plugin-office-addins".

(The package "eslint-plugin-office-addins" was not found when loaded as a Node module from the directory "[path-omitted]/outlookAddin".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-office-addins@latest --save-dev

The plugin "eslint-plugin-office-addins" was referenced from the config file in ".eslintrc.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

**Comment by TCourtneyOwen** [comment]
Can you please update to v.1.0.19. It's the latest version.

Thanks,

Courtney

**Comment by LoveSponge** [comment]
My version numbers provided above match the latest versions as can be seen on NPM.

[Plugin - 0.1.7](https://www.npmjs.com/package/eslint-plugin-office-addins)

[Config - 1.0.19](https://www.npmjs.com/package/eslint-config-office-addins)

Please re-open.
