### ISSUE TITLE
Could not start/run the Office Word Add-in

### ISSUE THREAD

**Issue by Manasa-Palugula** [OfficeDev/Office-Addin-Scripts#341]
Could not start/run the Word Add-in in VDI. After giving the "npm start" command in the VS Code terminal, its giving the below error. All the proxies and registry are set properly 

Error:
office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in 611defa3-8c64-4cc1-97eb-ef7f8e4f3a01. Debug method: 0
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Debugging started.
ApplicationInsights:CorrelationIdManager [
  Error: connect ETIMEDOUT 51.107.59.180:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '51.107.59.180',
    port: 443
  }
]

**Comment by arttarawork** [comment]
Hello, thanks for bringing attention to your issue!

Just to narrow down your issue, have you been entirely unable to start your office add-in, or have you previously been able to get it to run?

Have you run the `npm run stop` command prior to running `npm start` ? Sometimes, the nodejs server doesn't stop automatically after closing an add-in, so this helps make sure you're off to a good start. 

If that doesn't work right away, have you tried deleting the Office cache in `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\` ?

Let us know if the above solutions work for you!

**Comment by TCourtneyOwen** [comment]
We fixed this issue at one point. Maybe there's another issue.  

@Manasa-Palugula what version of office-addin-usage-data do you see in node_modules\office-addin-debugging\package.json in your project? The latest version is 1.0.20, so if you are running an older version of office-addin-usage-data, you may want to try updating the office-addin-debugging package to the latest version (3.0.39).

Thanks,

Courtney

**Comment by LouMM** [comment]
Please reopen if this is still an issue
