### ISSUE TITLE
Outlook Add-in with React & TypeScript application not rendering

### ISSUE THREAD

**Issue by roebuk** [OfficeDev/Office-Addin-Scripts#343]
# Prerequisites

Please answer the following questions before submitting an issue. 
- [*] I am running the latest version of Node and the tools
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

# Expected behaviour

I expect the app to render in the browser.

# Current behaviour

When visiting https://localhost:3000/taskpane.html in the browser the app doesn't render the app. office.js, vendor.js, taskpane.js all load with a valid 200 response.

I do receive  double the amount of logs in the console as I'd expect as if things are being executed twice:

```
[HMR] Waiting for update signal from WDS...
react-dom.development.js:21052 Download the React DevTools for a better development experience: https://fb.me/react-devtools
[HMR] Waiting for update signal from WDS...
react-dom.development.js:21052 Download the React DevTools for a better development experience: https://fb.me/react-devtools
Warning: Office.js is loaded outside of Office client
[WDS] Hot Module Replacement enabled.
[WDS] Live Reloading enabled.
[WDS] Hot Module Replacement enabled.
[WDS] Live Reloading enabled.
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Run `yo-office` with these settings

```
? Choose a project type: Office Add-in Task Pane project using React framework
? Choose a script type: TypeScript
? What do you want to name your add-in? TaskCreator
? Which Office client application would you like to support? Outlook
```

Run ```cd TaskCreator && npm run dev-server```

Open the browser and visit  https://localhost:3000/taskpane.html

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version: v14.15.1
* Office version: Unknown
* Tool version: Unknown

## Failure Logs

![image](https://user-images.githubusercontent.com/474377/100350134-58450f00-2fe1-11eb-9a87-9c656de98cec.png)

**Comment by awasser-omnispear** [comment]
I'll add my experience to this.  I'm working with an Excel app with React & TypeScript, and I have the same experience.  
Seems to work directly in Excel, though.

**Comment by villasv** [comment]
> I expect the app to render in the browser.

The browser won't load office-js, so if your react component rendering depends on it, it will never render.

In my root component is something along the lines of:

```typescript
export default class App extends React.Component<AppProps, AppState> {
  constructor(props: AppProps) {
    super(props);
    this.state = { isOfficeInitialized: false };
    Office.onReady(() => this.initApp());
  }

  private async initApp(): Promise<void> {
    const isOfficeApiSetSupported = Office.context.requirements.isSetSupported(
      "ExcelApi",
      this.props.excelApiRequirementSet
    );
    const lang = Office.context.contentLanguage.split("-")[0];
    await i18n.changeLanguage(lang);
    this.setState({ isOfficeInitialized: true, isOfficeApiSetSupported });
  }

  public render(): JSX.Element {
    if (!this.state.isOfficeInitialized) return <AppLoading />;
    if (!this.state.isOfficeApiSetSupported)
      return <AppUnsupported requirementSet={this.props.excelApiRequirementSet} />;
    ... the actual thing here...
  }
}
```

And when I visit the app from the browser, at least I get the rendering of my `AppLoading` component.
