### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by roebuk** [OfficeDev/Office-Addin-Scripts#344]
When setting up the project as per the documentation on https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator

After the documentation says to run `npm run dev-server` I can see there's a webserver running on localhost:3000 but there's no documentation to say where or how to view the application. It was only by browsing the issues on GitHub that I was made aware the application was actually online at https://localhost:3000/taskpane.html

It should be made explicit where to navigate to in order to view the application.

**Comment by TCourtneyOwen** [comment]
In order to use the add-in, you will need to follow the [Sideload Outlook add-ins for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing) outlined in the documentation.  Please let us know if that doesn't work for you.

Thanks,

Courtney
