### ISSUE TITLE
office-addin-manifest validate command should give an error if manifest path doesn't point to a file.

### ISSUE THREAD

**Issue by afisher** [OfficeDev/Office-Addin-Scripts#352]
# Expected behavior

Running `office-addin-manifest validate manifest` outputs the result of running against the validator.

# Current behavior

Running `office-addin-manifest validate manifest` outputs an error saying the service could not be contacted.

## Steps to Reproduce

`office-addin-manifest validate manifest`

Output is:
```
Error: Unable to contact the manifest validation service.
FetchError: request to https://validationgateway.omex.office.net/package/api/check failed, reason: socket hang up
```

## Context

* Operating System: Mac OS Catalina 10.15.7 
* Node version: v14.14.0
* Tool version: office-addin-manifest@1.5.12

**Comment by afisher** [comment]
My mistake, the path to the manifest file was wrong, it should be `manifest.xml` in the command.

**Comment by akrantz** [comment]
It would be useful for the command to detect that the manifest path does not correspond to a file and generate a good error message.

**Comment by TCourtneyOwen** [comment]
I will create a bug for this

**Comment by akrantz** [comment]
Why was this closed?

**Comment by millerds** [comment]
Courtney merged a PR for this almost 10 months ago.

**Comment by akrantz** [comment]
OK, great.
