### ISSUE TITLE
New ribbon icon images not showing

### ISSUE THREAD

**Issue by ziyaaktas** [OfficeDev/Office-Addin-Scripts#360]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [ x] I am running the latest version of Node and the tools
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

# Expected behavior

Changing ribbon icon images should be reflected in the Excel Office Add-in.

# Current behavior

Still seeing the old icons on dev & prod build.

**Comment by igor-ribeiiro** [comment]
We had some changes in our code and now we serve all the images files in the assets folders.
This issue should be fixed, please check and feel free to reopen if needed.
