### ISSUE TITLE
Documentation: Office-Addin-Dev-Settings

### ISSUE THREAD

**Issue by bgausden** [OfficeDev/Office-Addin-Scripts#368]
# Expected behavior
Documentation accurately lists supported webview options

From office-addins-dev-settings/commands.js:

```
function parseWebViewType(webViewString) {
    switch (webViewString ? webViewString.toLowerCase() : undefined) {
        case "ie":
        case "ie11":
        case "internet explorer":
        case "internetexplorer":
            return devSettings.WebViewType.IE;
        case "edge":
        case "spartan":
            return devSettings.WebViewType.Edge;
        case "edge chromium":
        case "edgechromium":
        case "anaheim":
            return devSettings.WebViewType.EdgeChromium;
        case "default":
        case "":
        case null:
        case undefined:
            return undefined;
        default:
            throw new Error(`Please select a valid web view type instead of '${webViewString}'.`);
    }
}
```

# Current behavior
[Documentation ](https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-dev-settings/README.md#webview)lists invalid webview options

>webview
>Switches the webview runtime in Office for testing and development scenarios.
>
>Office must be running on the Beta channel to switch runtimes
>
>Syntax:
>
>office addin-dev-settings webview <manifest> <web-view-type>
>
>manifest: path to manifest file.
>
>runtime: Office webview to load ('edge' or 'edge-chromium, 'edge-legacy', 'ie', or 'default').

**Comment by arttarawork** [comment]
Hi @bgausden, thanks for catching this! I'll send through the correction shortly.

**Comment by arttarawork** [comment]
@bgausden The commander.js file has actually been updated already, and the changes are in master. Have you pulled the latest changes from master?

**Comment by bgausden** [comment]
I think this is a doc project issue. Re-raise there?

**Comment by akrantz** [comment]
@bgausden The values listed in the documentation are the ones that what we want to document. We kept some older ones in the code that used code names like "anaheim" or older values like "edgechromium" to maintain backward compatibility but we've normalized the names using "edge-chromium" and "edge-legacy" to better distinguish. 

This page provides more info as well about the webview types: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
