### ISSUE TITLE
office-addin-sso - configure.ts -> Company Administrator/Global Administrator error

### ISSUE THREAD

**Issue by Casper-Olsen** [OfficeDev/Office-Addin-Scripts#370]
# Prerequisites

- [*] I am running the latest version of Node and the tools
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

# Expected behavior

When running `npm run configure-sso` the expected behavior is for the Application to be successfully registered in Azure.

# Current behavior

When running `npm run configure-sso` I get the following error:
```
Opening browser for authentication to Azure. Enter valid Azure credentials
Login was successful!
Registering new application in Azure
Application was successfully registered with Azure
Setting identifierUri
Setting signin audience
(node:16812) UnhandledPromiseRejectionWarning: Error: Unable to determine if user is tenant admin:
ERROR: Bad Request({
  "error": {
    "code": "Request_BadRequest",
    "message": "Invalid object identifier 'members'.",
    "innerError": {
      "date": "2021-01-20T12:02:41",
      "request-id": "...",
      "client-request-id": "..."
    }
  }
})

    at Object.<anonymous> (...\node_modules\office-addin-sso\lib\configure.js:155:19)
    at Generator.throw (<anonymous>)
    at rejected (...\node_modules\office-addin-sso\lib\configure.js:4:65)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:16812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If i change from `"Company Administrator"` to `"Global Administrator"` in configure.js, it works as expected.
https://github.com/OfficeDev/Office-Addin-Scripts/blob/848756532b8b57e7edbaf99f9c322c0c2250c5af/packages/office-addin-sso/src/configure.ts#L115

The Application is successfully created.  

```
Opening browser for authentication to Azure. Enter valid Azure credentials
Login was successful!
Registering new application in Azure
Application was successfully registered with Azure
Setting identifierUri
Setting signin audience
Setting application secret
App secret is ...
Adding application secret for SSO to Windows Credential Store
Updating source files with application ID and port
Logging out of Azure now
Application with id ... successfully registered in Azure.  Go to https://ms.portal.azure.com/#home and search for 'App Registrations' to see your application
```

I found the following information about Global Administrator / Company Administrator:
<https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#global-administrator--company-administrator>
So it seems that it is referred to by both names.
Now I don't know why "Global Administrator" is required in my scenario to make it work and why it does not work with "Company Administrator".  
Is this something that has to be changed or perhaps both have to be supported?

## Steps to Reproduce

1.
Create a new project with `yo office`.  
```
? Choose a project type: Office Add-in Task Pane project supporting single sign-on
? Choose a script type: JavaScript
? What do you want to name your add-in? SSO
? Which Office client application would you like to support? Outlook
```
Which runs `npm install`.

2.
Run `npm run configure-sso` and login with Azure Credentials.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 Enterprise 1909
* Node version: v12.14.1
* Office version:
* Tool version: office-addin-sso@1.0.28

**Comment by kdubious** [comment]
Same error for me today.

**Comment by TCourtneyOwen** [comment]
We recently published a fix that I think will address this issue. Please try updating office-addin-sso to v.1.0.30.

Thanks,

Courtney
