### ISSUE TITLE
npm start will not run dev server under npm v7

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/Office-Addin-Scripts#394]
# Expected behavior

With an Excel add-in project, when running the command `npm start` expect the node.js server to start running, and then Excel to open in debug mode.

# Current behavior

`npm start` launches Excel, but not the dev server

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Do not use VS Code (it caches variables that affect these steps)

1. From command prompt, run `yo office --projectType excel-functions --name 'testExcelAdd-in' --host excel --js`
2. Run `cd testExcelAdd-in`
3. Run `npm start`

At this point Excel will open, but the dev server is not running, so the add-in fails to load properly.
Workaround is to run `npm run dev-server` to start the server, and then the add-in works.

From Adam:
Looks like NPM v7 has changed npm run so it does not put the package.json scripts into the environment.  We used this to look for the "dev-server" script defined in package.json so we could run it if not already running.
https://github.com/npm/cli/blob/latest/CHANGELOG.md#all-lifecycle-scripts
https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md

Could perhaps write a generic npm package that can take what would have been the npm env var, and instead look for the env var for package.json, and read package.json to get the value. For example, replace `npm_package_script_dev-server` with `npmEnv("npm_package_scripts_dev_server")`.

## Context

* Operating System: Windows 10
* Node version: 14.16.0
* Office version: 
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by igor-ribeiiro** [comment]
This was fixe on https://github.com/OfficeDev/Office-Addin-Scripts/pull/404. Closing this issue.
