### ISSUE TITLE
Unable to install the CA certificate. Import-Certificate : Cannot find drive. A drive with the name 'cert' does not exist.

### ISSUE THREAD

**Issue by Geraint87** [OfficeDev/Office-Addin-Scripts#408]
# Expected behavior
I expected to be able to clone the repo from MS, follow the installation instructions and try out the Custom Functions Batching solution.

# Current behavior
I get an error in the build step, where it can't find the location of the certificates.

## Steps to Reproduce

I run the first two steps in the README to `npm install` and then `npm run build`.

After installing, there are a number of vulnerability errors/warnings, but I have tried continuing with and without running npm audit fix on these without luck.

Then when I run npm run build, it fails at the certificate generating step with the following error:
`Cannot find drive. A drive with the name 'cert' does not exist.`

I am running the console as Admin, on Windows 10. I have tried manually installing the certificates from the `%USERDATA%\.office-addin-dev-certs` folder and that has not worked either. 

I have also deleted and recreated that folder, and I still get the same error when running `npm run build` on this project.

## Context

* Operating System: Windows 10
* Node version: 7.7.0
* Office version: 2016
* Tool version: ?

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by LouMM** [comment]
Team to attempt to test this and report back.

**Comment by igor-ribeiiro** [comment]
Hi @Geraint87, sorry for the delay. Are you still running into this problem? I just tried cloning the project and running the build in an admin prompt and I didn't run into any certificate errors.

I also noticed that you are currently running on node 7.7.0, while the current default for this project is node 14. I just tried with node 14.16.0

Could you please try to upgrade your node and report back? I also checked when I installed the packages and there were no packages vulnerabilities.

**Comment by igor-ribeiiro** [comment]
@Geraint87 I will be closing this issue for now as I didn't get any return.
Feel free to open the issue again if you still need it.
