### ISSUE TITLE
custom-functions-metadata-plugin triggering deprecation warnings on Webpack 5

### ISSUE THREAD

**Issue by villasv** [OfficeDev/Office-Addin-Scripts#421]
Just a heads up from the future. In my setup with Webpack 5, I'm getting these warnings:

```
(node:8984) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
...
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

Plus, this piece of code:

```
                if (module._source && module._source._name.endsWith(inputFilePath)) {
                    generateResult.associate.forEach((item: { id: string; functionName: string; }) => {
                        module._source._value += `\nCustomFunctions.associate("${item.id}", ${item.functionName});`;
                    });
                }
```

With webpack 5 on Windows, the condition never passes and the `CustomFunctions.associate` calls are never added to the output. Probing around, it looks like `module._source._name` is morphed into `webpack://data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;` by the time that callback is involved.

**Comment by villasv** [comment]
My suggestions to fix the warnings:

Change this hook
```typescript
        compiler.hooks.compile.tap(pluginName, async () => {
            generateResult = await generateCustomFunctionsMetadata(inputFilePath, true);
        });
```
To use beforecompile.tapPromise
```typescript
        compiler.hooks.beforeCompile.tapPromise(pluginName, async () => {
            generateResult = await generateCustomFunctionsMetadata(inputFilePath, true);
        });
```

**Comment by akrantz** [comment]
@villasv Thanks for raising this issue and looking into it. We would welcome a pull request if you would like to contribute.

If we can validate that these work with webpack 4 also, then it shouldn't be a problem making the change.

**Comment by villasv** [comment]
I'm still trying to figure out the `module._source._name` part. If I can make it work, I'll send a PR with all related changes.

**Comment by igor-ribeiiro** [comment]
Hi @villasv, I'm currently trying to reproduce this issue but I'm having troubles with it.
1) We are already using webpack v5 right?
2) Which commands did you run to get this deprecation warning? By building the project normally I'm not getting these warnings

I think the fact your project is not building could be a package-lock.json issue. I will be sending a PR soon updating it and hopeful you should be able to build the project after that.

**Comment by akrantz** [comment]
You need to validate the custom-functions-metadata-plugin in a custom functions project from Yo Office which is using Webpack 4, and also in another instance where webpack is updated to version 5.

**Comment by villasv** [comment]
> We are already using webpack v5 right?

"We" as in the dependency, yes. But the plugin is used by Webpack 4 in the projects generated by the templates (like https://github.com/OfficeDev/Office-Addin-TaskPane-React)

> Which commands did you run to get this deprecation warning? By building the project normally I'm not getting these warnings

`npm run build`, or more generally, any command that triggers Webpack to build (like ` webpack serve`).
