### ISSUE TITLE
Outlook addin SSO - Publish guidelines

### ISSUE THREAD

**Issue by spoman007** [OfficeDev/Office-Addin-Scripts#452]
Are there any guidelines to publish the Outlook addin with SSO to production?

I was trying to publish the addin using Azure Storage static web option. Howerver I am facing issue with mismatch between the Azure AD App API URL and Azure Storage Static web URL.

The plugin manifest does not allow the api and resource to be different.

![image](https://user-images.githubusercontent.com/8514338/118399235-82a48a80-b65c-11eb-8f99-e8c887b01dee.png)

Is this the correct way to publish SSO enabled plugin? Is there a link to documentation which I can follow.

**Comment by davidchesnut** [comment]
Hi @spoman007,

You can't use a static web site with SSO. Please take a look at this [discussion thread](https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/issues/61#issuecomment-821517972) for some notes on how to deploy.

Hope this helps!
David

**Comment by igor-ribeiiro** [comment]
We will be closing for now, fell free to reopen if there are more questions!
