### ISSUE TITLE
Debugging doesn't appear to work

### ISSUE THREAD

**Issue by tgoyer** [OfficeDev/Office-Addin-Scripts#453]
# Expected behavior
I expect to be able to debug my vanilla scaffolded project.

# Current behavior
I created a brand new "yo office" scaffolded Excel Addin project and `npm start` started it.
When I run F12 (IEChooser.exe), I get no listed projects.  
When I run the VSCode Office Addin-Debugger, I get the following error: 
`[vscode-debugger-extension-for-office-addins] Error processing "attach": connect ECONNREFUSED 127.0.0.1:9222`

## Steps to Reproduce
1. Scaffold vanilla Excel addin (yo office)
2. npm install && npm start
3. Hit "Show Taskpane" in Excel
4. Load debuggers

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:  Win 10 64-bit
* Node version:  v.14.17.0
* Office version:  Excel 365
* Tool version:
```
    "office-addin-cli": "^1.0.17",
    "office-addin-debugging": "^4.0.3",
    "office-addin-dev-certs": "^1.5.12",
    "office-addin-lint": "^1.1.4",
    "office-addin-manifest": "^1.5.16",
    "office-addin-prettier-config": "^1.0.14",
    "office-addin-test-helpers": "^1.0.28",
    "office-addin-test-server": "^1.0.37",
```

**Comment by akrantz** [comment]
You might be running the Edge Chromium webview2.  You can check what is being used based on this article:

https://developer.microsoft.com/en-us/office/blogs/understanding-office-add-ins-runtime/

![image](https://user-images.githubusercontent.com/741153/118870126-0cda3200-b89b-11eb-9fe1-1613c64dc219.png)

**Comment by tgoyer** [comment]
My dialog has this:
---------------------------
Security Info
---------------------------
URL: https://localhost:3000/taskpane.html
SSL: On
---------------------------
OK   
---------------------------

**Comment by jmayermsi** [comment]
Can you elaborate on this @akrantz ?  thought the expected and desired behavior at this point is to use webview2. We are also getting crashes of the panel in Excel. Bumping **office-addin-debugging** to v4 would that help the issuue

**Comment by akrantz** [comment]
This isn't related to office-addin-debugging. 

I have an add-in that I wrote which can show the browser info. Do this:
1. Download this manifest file: https://akrantz.github.io/office-addins/browser-info/manifest.prod.xml
2. In a command window, go to the directory containing the manifest and run:
    `npx office-addin-dev-settings register manifest.prod.xml`
3. Start (or restart) Excel.
4. On Insert menu, click the drop-down arrow next to My Add-ins, and click "Browser Info" under Developer Add-ins.
5. On the Home menu, click the Browser Info button.

You'll get a task pane which shows the browser.
![image](https://user-images.githubusercontent.com/741153/118921532-2dcb7300-b8ed-11eb-9ca9-3792d97d1f62.png)

**Comment by jmayermsi** [comment]
@akrantz Thanks for putting this up. I had to use centralized deployment to use the extension but it reports the same Browser version you listed here in my case. Still stumped right now on this

**Comment by akrantz** [comment]
If you're using Edge Chromium, you should be able to click in the task pane webview and press F12 to bring up the Edge dev tools. You won't need the older IEChooser.exe dev tools.

**Comment by tgoyer** [comment]
@akrantz  Thanks for the assistance.  When I run your addin, I get the following:
![image](https://user-images.githubusercontent.com/7535578/119178605-8f95f500-ba33-11eb-8900-4753c35d84e3.png)

Should I upgrade to Edge Chromium?  Will Office pick that up automatically as the browser to use?

Thanks

**Comment by tgoyer** [comment]
@akrantz I tried installing the WebView2 distro from https://developer.microsoft.com/en-us/microsoft-edge/webview2/ but I still get the Microsoft Edge (EdgeHTML) result from your browser addin.  It there a command I can run to enable it?

**Comment by akrantz** [comment]
You can use `npx office-addin-dev-settings webview` to specify a preference for the webview type when debugging a particular add-in.

```
c:\dev>npx office-addin-dev-settings webview --help
Usage: office-addin-dev-settings webview [options] <manifest-path> [web-view-type]

Specify the type of web view to use when debugging. Windows only.

Options:
  -h, --help  display help for command

For [web-view-type], choose one of the following values:

        'edge' or 'edge-chromium' for Microsoft Edge (Chromium)
        'edge-legacy' for the legacy Microsoft Edge (EdgeHTML)
        'ie' for Internet Explorer 11
        'default' to remove any preference

Omit [web-view-type] to see the current setting.
```

**Comment by akrantz** [comment]
The preference may not be honored if the webview type is not available or the Office version doesn't support that, but in general it should take effect.

**Comment by igor-ribeiiro** [comment]
Hey @tgoyer, we will be closing thi for now. If you fell you need more help, please reopen this issue!
