### ISSUE TITLE
Update webpack to be a peerDependency in 'custom-functions-metadata-plugin'?

### ISSUE THREAD

**Issue by AlbertGozzi** [OfficeDev/Office-Addin-Scripts#455]
# Expected behavior

When developing an Excel add-in, one should be able to use both 'react' and 'custom functions'.

# Current behavior

Current dependency configuration in the 'custom-functions-metadata-plugin' makes the combined project crash, because of a bug with multiple webpack versions. **Updating webpack from being a dependency to a peerDependency in the 'custom-functions-metadata-plugin' might solve the issue.**

I've been trying to merge two of the default yeoman templates, React and CustomFunctions. After copying the necessary packages, and updating the manifest and the webpack configuration, npm start crashes with the following error:

`The 'compilation' argument must be an instance of Compilation`

I've been able to find other issues where this is discussed (such as [here](https://github.com/jantimon/html-webpack-plugin/issues/1451)), and it seems to be an issue with having two versions of webpack running at the same time. This made me realize that the ['custom-functions-metadata-plugin'](https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/custom-functions-metadata-plugin/package.json) was listing webpack as a dependency as opposed to a peer dependency, therefore installing a second version of webpack in my project. 

Manually removing the webpack dependency from the package-lock.json solved the issue for me, but thought it would be good to raise the issue!

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a React project via Yeoman
2. Create a Custom Functions project via Yeoman
3. Manually update package.json, manifest and webpack config in 1. to include relevant sections from 2.
4. Start the dev server

**Comment by millerds** [comment]
If it is simply a problem with the different versions of webpack then the custom functions project wouldn't work by itself because it's using the same version as the react project.  Seem like there is something in the merge you are doing.  You might try starting the the Custom Functions project and add the necessary react components (the reverse of what you are describing here).

**Comment by prosaiexe** [comment]
Running into the same error when trying to run 'npm build' trying to merge an Excel React add-in with Custom Functions. 

Would be nice if there was an example official repo with both React and Custom Functions together as there seems to be others trying to do the same thing and merge the templates.

**Comment by OttoLaitinen** [comment]
I was running into this same problem. I solved it by adding a `postinstall` script to the `package.json`, which removes webpack from custom-functions-metadata-plugin's node_modules. It is ugly but it works 😅

`"postinstall": "rm -rf ./node_modules/custom-functions-metadata-plugin/node_modules/webpack"`

**Comment by neittien0110** [comment]
I had the same problem.  Everything is okay until I run  _npm update_ .  **Webpack** was upgraded from version 4 to version 5. **custom-functions-metadata-plugin** was upgraded from 1.0.40 to 1.0.54,  The error happened.
![image](https://user-images.githubusercontent.com/8079397/121772255-7e598780-cb9e-11eb-8674-c219050c1eba.png)

**Comment by neittien0110** [comment]
> I was running into this same problem. I solved it by adding a `postinstall` script to the `package.json`, which removes webpack from custom-functions-metadata-plugin's node_modules. It is ugly but it works 😅
> 
> `"postinstall": "rm -rf ./node_modules/custom-functions-metadata-plugin/node_modules/webpack"`

Thank you so much @OttoLaitinen . As your advice, I fixed this issue.

In my case, everything was okay until I ran  _npm update_ .  The error happened and:
 -  **webpack** was upgraded from version 4 to version 5.  
 -  But **webpack-cli** and **webpack-dev-server** were not changed.
![image](https://user-images.githubusercontent.com/8079397/121772943-f4f88400-cba2-11eb-8c2e-1829e229127b.png)
 -  **custom-functions-metadata-plugin** was upgraded from 1.0.40 to 1.0.54,  
![image](https://user-images.githubusercontent.com/8079397/121772647-da251000-cba0-11eb-9b13-9869d0c91b79.png)
 - In the folder node_modules, there are 2 folder **custom-functions-metadata** and **custom-functions-metadata-plugin**
![image](https://user-images.githubusercontent.com/8079397/121772543-23c12b00-cba0-11eb-9c29-ec752de7e595.png)

**Comment by neittien0110** [comment]
> I was running into this same problem. I solved it by adding a `postinstall` script to the `package.json`, which removes webpack from custom-functions-metadata-plugin's node_modules. It is ugly but it works 😅
> 
> `"postinstall": "rm -rf ./node_modules/custom-functions-metadata-plugin/node_modules/webpack"`

Thank you so much, @OttoLaitinen. As your advice, I fixed this problem.

In my case, everything was okay until I ran  _npm update_ .  The error happened and:
 -  **webpack** was upgraded from version 4 to version 5.  
 -  But **webpack-cli** and **webpack-dev-server** were not changed.
![image](https://user-images.githubusercontent.com/8079397/121772943-f4f88400-cba2-11eb-8c2e-1829e229127b.png)
 -  **custom-functions-metadata-plugin** was upgraded from 1.0.40 to 1.0.54,  
![image](https://user-images.githubusercontent.com/8079397/121772647-da251000-cba0-11eb-9b13-9869d0c91b79.png)
 - In the folder node_modules, there are 2 folder **custom-functions-metadata** and **custom-functions-metadata-plugin**
![image](https://user-images.githubusercontent.com/8079397/121772543-23c12b00-cba0-11eb-9c29-ec752de7e595.png)

I wonder that if the version of webpack, webpack-cli could be the cause of is bug.

**Comment by millerds** [comment]
Looking at Excel-Custom-Functions in isolation what's currently in the repo works.  However it has vulnerabilities listed and while most of those can be corrected just fine, there are three updates that cause problems when updated: copy-webpack-plugin, webpack, and custom-functions-metadata-plugin.  Of those custom-functions-metadata-plugin was only listed as a minor version update which means it gets updated more easily and is the trigger of the indicated error.  It probably should have had a major version update when the webpack dependency shifted major versions (instead of version to 1.0.44).  If you leave custom-functions-metadata-plugin at the lower version and update webpack and copy-webpack-plugin in excel-custom-functions project instead you will get other error requiring webpack configuration updates.

In thinking about the plugin itself . . . I'd have to consider moving webpack from a dependency to a peerdependency more closely.

**Comment by pk8189** [comment]
> "postinstall": "rm -rf ./node_modules/custom-functions-metadata-plugin/node_modules/webpack"

I was hitting the same error so I tried using the above but I get this error
```
/node_modules/custom-functions-metadata-plugin/lib/customfunctionsplugin.js:39
                compilation.assets[this.options.output] = new webpack_1.sources.RawSource(generateResult.metadataJson);
                                                                                ^
TypeError: Cannot read property 'RawSource' of undefined
    at /node_modules/custom-functions-metadata-plugin/lib/customfunctionsplugin.js:39:81
```
which looks like a failure at `require webpack`
what is the best way to get around this issue or is there a fix for the main issue?

**Comment by ozcanonur** [comment]
I am also hitting the same issue as @pk8189.
