### ISSUE TITLE
Cannot sideload an Office document without an existing webextension xml part

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/Office-Addin-Scripts#500]
# Expected behavior

The --document parameter can be used to specify an existing document to sideload. For sideload to web, this is the url of the document. For sideload to desktop, this is the file path to an existing document.

For sideload to desktop, if the specific document doesn't contain a webextension xml part, one should be added so it contains a reference to the add-in, thereby causing the add-in to be loaded when the document is opened.

NOTE: When sideload to web was implemented and the --document parameter added, we intentionally did work to support sideload to desktop for an existing document with a webextension part, but did not do the work to support it for arbitrary documents. I'm creating this issue to track this as some customers have asked and we haven't been clear about this.

# Current behavior

Sideload to desktop for an existing document without a webextension part will give an error.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. "npm start manifest.xml --document <path to Office document without webextension part>"

**Comment by igor-ribeiiro** [comment]
This feature request should be fixed when https://github.com/OfficeDev/Office-Addin-Scripts/pull/564 goes live.
