### ISSUE TITLE
office-addin-dev-certs install - Subject is "127.0.0.1" rather than "localhost"

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/Office-Addin-Scripts#514]
# Expected behavior

The certificate created in users\name\.office-addin-dev-certs\localhost.crt should have a Subject of "localhost"
![image](https://user-images.githubusercontent.com/28546239/130135510-ebacd452-8de8-4986-8474-84462472cc1c.png)

It would be useful to add a -Subject parameter to let the user specify "localhost".

# Current behavior

The certificate is Subject "127.0.0.1" which fails with certificate errors for https://localhost:3000 which is the normally documented URL for yo generated Office Add-In.
![image](https://user-images.githubusercontent.com/28546239/130135534-d754ca3a-4d51-453a-af9b-59dae594f01b.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

`npx office-addin-dev-certs install --machine --days 365`

https://localhost:3000 fails with a untrusted certificate.

The workaround is either to manually install the certificate from a Browser session or to change the package.json line from the default
`"dev-server": "webpack-dev-server --mode development --hot --config webpack.dev.js",`
to 
`"dev-server": "webpack-dev-server --host 127.0.0.1 --mode development --hot --config webpack.dev.js",`

## Context
`npm run dev-server`
developing Office add-ins

* Operating System: Windows 10
* Tool version: "office-addin-dev-certs": "^1.5.21",

## Failure Logs
```
package.json snippet:
  "config": {
    "app-to-debug": "outlook",
    "app-type-to-debug": "desktop",
    "dev-server-port": 3000,
    "manifestFile": "manifest-3000.xml"
  },
```
While it's possible to change the host for webpack-dev-server Windows Outlook complains the Add-In is not trusted.
![image](https://user-images.githubusercontent.com/28546239/130137957-aa67438a-a8f2-417e-be20-417a1580999d.png)
OWA however is happy to run the Add-In.

**Comment by millerds** [comment]
@timothyhoffmann sorry for not looking into this more quickly.  When looking at this I see the subject as the IP address in the cert file, but the certificate store has " Developer CA for Microsoft Office Add-ins" as both the issuer and the subject.  I am unable to repro the cert issue you descript.  However, we have made some improvements to the cert management tools so you might want to try with projects created with current templates.

**Comment by millerds** [comment]
If there are any further problems, please log a new issue.  We will look into the linked issue #745.

**Comment by mabuelhagag** [comment]
I had the same problem but what worked for me was replacing all references of `localhost` to `127.0.0.1`
