### ISSUE TITLE
extend getGraphToken to getSharePointToken

### ISSUE THREAD

**Issue by jonathanhotono** [OfficeDev/Office-Addin-Scripts#516]
# Prerequisites

- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Is there any way to get sharepoint token SSO using this package? Can we extend getGraphToken to getSharePointToken?
Is it possible to authenticate to both graph & sharepoint scope?

**Comment by millerds** [comment]
We just have this sample that makes the the service call to get the graph token.  If you want to do more then that it's something you will have to build.
