### ISSUE TITLE
It should be possible to register and sideload the office add-in without dev server

### ISSUE THREAD

**Issue by jfoclpf** [OfficeDev/Office-Addin-Scripts#540]
I don't upload the `dist` files from webpack to `localhost`, but to some other URL, thus it should be possible to only register and sideload the office add-in without starting the dev server at `localhost`. How to do that with `office-addin-debugging`?

**Comment by jfoclpf** [comment]
I mean, I simply wanted to automatically sideload an addin without all the attached dev server initialization

**Comment by akrantz** [comment]
If you change the `dev-server` script in package.json, it can run whatever you want, or if not present, it won't run the dev-server. The office-addin-debugging start command also has a `--dev-server` parameter if you want to provide a different command line to run when debugging is started. If falls back to the package.json script if a parameter isn't provided.
