### ISSUE TITLE
Unable to debug sideloaded addin in Excel on web

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/Office-Addin-Scripts#550]
I was following this page to debug my Excel AddIn on the web
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-in-office-online
The difference at my end is I didn't manually insert and sideload addin, instead, I called
await startDebugging(manifestPath, {
        app: toOfficeApp(host),
        appType: AppType.Web,
        devServerCommandLine: devServerCmd,
        devServerPort: devServerPort,
        enableDebugging: true,
        document: 'xxxxxxxxxxxxxxx'
    });
to sideload my addin in the specifcied Excel document. Since my addin has no command so it just auto sideloaded.

# Expected behavior
Press F12 I should able to find my addin's Javascript files by searching through Ctrl+P 

# Current behavior
Unable to search my addin's Javascript files and debug them

## Steps to Reproduce
1. sideload addin in Excel on web
2. press F12

## Context
* Operating System: Win10
* Node version: 
* Office version: Office 365
* Tool version: 

## Failure Logs
![Capture](https://user-images.githubusercontent.com/26646767/139928928-e994745f-136b-4ded-8384-c3c6a895fdc3.PNG)

**Comment by millerds** [comment]
Can you try running 'npm run start:web -- --document <url>' where '<url>' is the url of that document you want to test with and see what the tooling shows you then?

**Comment by igor-ribeiiro** [comment]
I will be closing this thread since no answer was received in the previous days.
Fell free to reopen this thread if the problem still persists.
