### ISSUE TITLE
The script office-addin-manifest reports manifest as valid, but Outlook cannot install it.

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/Office-Addin-Scripts#554]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [ *] I am running the latest version of Node and the tools
- [ *] I checked the documentation and found no answer
- [ *] I checked to make sure that this issue has not already been filed

# Expected behavior
Outlook installs my addin manifest file.

# Current behavior
Outlook cannot install my manifest file.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. unpack attached archive.
2. in the folder with archive content, find manifest file
3. validate the manifest file with office-addin-manifest script:
3.1 in Terminal.app execute the command:
office-addin-manifest validate MyOutlookAddin.xml
4. Note that the script reports manifest file as valid:
The manifest is valid
5. Install the latest Outlook from AppStore
6. Try to add custom addin from attached manifest to Outlook.
7. Installation failed

NOTE: It seems, that the issue in the minimal requirement set.
When I setup 1.3 requirement set:
`
 <Requirements>
        <Sets DefaultMinVersion="1.3">
            <Set Name="Mailbox" />
        </Sets>
 </Requirements>
`
The installation is successful, and my addin works well.

But, when I setup 1.4 requirement set - installation fails.

What version of Outlook should I use to have access to requirement sets 1.4 and above?
Where can I download that version?

Why the office-addin-manifest script does not report exact version of Outlook? 

I decided to submit this issue, because the script reports manifest file as valid, but Outlook cannot install it.

May be the issue in the Outlook version, but it confuses me, because I use the latest version from AppStore.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOs BigSur 11.6 MacBook Air (M1, 2020)
* Node version: v14.18.0.
* Office version: 
* Tool version: Microsoft Outlook for Mac 16.54 (21101001)

## Failure Logs

[office-addin-manifest-issueFiles.zip](https://github.com/OfficeDev/Office-Addin-Scripts/files/7521462/office-addin-manifest-issueFiles.zip)
Please include any relevant log snippets, screenshots or code samples here.

**Comment by igor-ribeiiro** [comment]
@DanilKorotenko Thanks for raising this issue!
I'm not sure if we already support the 1.4 version as you are asking, as our templates are using the 1.3 version for now.

I will create an internal bug for us to track your request.
It would be:
"Make manifest validation also check the `DefaultMinVersion` of the mailbox".
Let me know if this works for you.

**Comment by DanilKorotenko** [comment]
I see here a confusing behaviour of Outlook application.

When I install my addin through Office 365 admin center, it supports 1.8 requirement set and my addin works well.

When I install my addin through "Add custom addin" in Outlook application, I see the situation described above: Outlook cannot install my addin.

But,
In this article:
https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#outlook

I have read that starting from version 16.38.506 for Mac, Outlook supports requirement sets up to 1.8.

Please, clarify this situation.
I do not understand, why Outlook cannot add the custom addin with 1.8 requirement set. But in the same time it adds the addin with 1.8 requirement set installed from Office 365 Admin center.

**Comment by igor-ribeiiro** [comment]
Hi @DanilKorotenko, I tried it on Windows, so the message might be a little different from the Mac one.
Note that, validation API that you are using performs a subset of validation. An add-in goes through more validations before getting published. Validation API being successful doesn’t mean that add-in is valid, so this is probably what you facing.

The first time when Custom Outlook add-in is uploaded, we always get “Installation Failed” error. But the second time, it gives a proper validation error.

First-time error message:
![image](https://user-images.githubusercontent.com/18221895/144503895-a03e8be8-5c9b-4b89-8422-3e3633da4d0c.png)

second-time error message:
![image](https://user-images.githubusercontent.com/18221895/144503902-2f1771f6-0556-43b3-8051-4d4702576806.png)

That might be what is causing confusion. Could you check that you get this second error message?
It might solve your problem.

**Comment by DanilKorotenko** [comment]
Unfortunately, I didn't get the second error message.
If I did, I would not file this issue.

Thanks for clarification!

**Comment by DanilKorotenko** [comment]
Finaly, the issue is:

Manifest validation script does not report version mismatch between VersionOverridesV1_1 and base manifest.

Steps to reproduce:
1. Validate attached manifest with the script.

Expected result:
Script reports:
The min API requirement 1.3 specified in override VersionOverridesV1_1 is lower than min API requirement specified in base manifest.

Actual result:
Script reports:
Manifest is valid
[MyOutlookAddin_incorrect.xml.zip](https://github.com/OfficeDev/Office-Addin-Scripts/files/7649393/MyOutlookAddin_incorrect.xml.zip)
.

**Comment by igor-ribeiiro** [comment]
@DanilKorotenko The validation should be fixed and working right now!
I will be closing this issue as it should be fixed, but if you are still experiencing problems, please, feel free to reopen it!
