### ISSUE TITLE
office-addin-mock, crash on context.load when > 1 items in the mock array

### ISSUE THREAD

**Issue by tomprod** [OfficeDev/Office-Addin-Scripts#561]
# Expected behavior

With a mock object for context.document.body.search, have an items property with multiple elements, eg: [{text: 'A'}, {text: 'B'}]

const words = context.document.body.search(...);
context.load(words, 'text');

_expected behavior:_ no crash on context.load with error "1 navigational property must be present in object model before calling context.load" (i tried with various syntaxes in context.load, "items/text/*", "items/text" ...

# Current behavior

crash on context.load with error "1 navigational property must be present in object model before calling context.load" whenever the returned array has > 1 item

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 20H2 build 19042.1348
* Node version: 14.17.0
* Office version: N/A 
* Tool version: 1.0.1

## Failure Logs

_Test code with jest :_
```
it('should not crash', async () => {
    const WordFields = [ { text: 'A' }, {text: 'B' } ];
    const MockData = {
      context: {
        document: {
          body: {
            search: function () {
              return {
                items: WordFields,
              };
            },
          },
        },
        items: WordFields,
      },
      run: async function (callback) {
        return await callback(this.context);
      },
    };

    const contextMock = new OfficeMockObject(MockData) as any;
    global.Word = contextMock;

    await Word.run((context) => {
      const foundWords = context.document.body.search('pattern', {
          matchWildcards: true,
          matchCase: false,
        });
     context.load(foundWords, 'text'); // <-- crashes here whenever there is > 1 item in items (=WordFields in mock object in this case)
    }     
}); 
```
     

_Output :_ 

Error: Navigational property 1 needs to be present in object model before load is called.

    at OfficeMockObject.loadNavigational (officeMockObject.ts:131:15)
    at officeMockObject.ts:113:16
    at Array.forEach (<anonymous>)
    at OfficeMockObject.loadMultipleProperties (officeMockObject.ts:112:10)
    at officeMockObject.ts:51:12
    at Array.forEach (<anonymous>)
    at OfficeMockObject.load (officeMockObject.ts:50:16)
    at FusionService.<anonymous> (Fusion.service.ts:87:17)
    at step (Fusion.service.ts:9979:19)
    at Object.next (Fusion.service.ts:9709:14)
    at fulfilled (Fusion.service.ts:9596:24)

**Comment by igor-ribeiiro** [comment]
Thanks for raising this issue @tomprod. It is real and the following PR should close this #562
