### ISSUE TITLE
office-addin-mock, crash when trying to use a mocked function inside a mocked object of an array

### ISSUE THREAD

**Issue by tomprod** [OfficeDev/Office-Addin-Scripts#563]
# Expected behavior

Be able to mock a function inside a mock object, for example, an object returned by context.document.body.search, such as [{text: 'A', insertText: (text, insertLocation) => { mySpyingVariable = text; } }]

The framework seems to allow it but doesn't (yet/fully) support it

# Current behavior

For now, doing the above and trying to use the mocked function, will throw an exception "Error: Property insertText needs to be present in object model before load is called."

## Steps to Reproduce

```
 let spyVariable = null;


 const WordFields = [ { text: 'A', insertText: (text, insertLocation) => {
    spyVariable = text;   
   } 
} ];
    const MockData = {
      context: {
        document: {
          body: {
            search: function () {
              return {
                items: WordFields,
              };
            },
          },
        },
        items: WordFields,
        InsertLocation: {
          replace: {]
        },
      },
      run: async function (callback) {
        return await callback(this.context);
      },
    };

 const contextMock = new OfficeMockObject(MockData) as any;
    global.Word = contextMock;

    await Word.run((context) => {
      const foundWords = context.document.body.search('pattern', {
          matchWildcards: true,
          matchCase: false,
        });
       foundWords[0].insertText("test", InsertLocation.replace); //  <-- crashes here with "Error: Property insertText needs to be present in object model before load is called." (yes because insertText is not a property ! :-)  )
    }     

```

## Context

* Operating System:
* Node version:
* Office version:
* Tool version: 1.0.1

## Failure Logs

Error: Property insertText needs to be present in object model before load is called.

    at officeMockObject.ts:178:15
    at Array.forEach (<anonymous>)
    at OfficeMockObject.parseObjectPropertyIntoArray (officeMockObject.ts:160:29)
    at officeMockObject.ts:168:22
    at Array.forEach (<anonymous>)
    at OfficeMockObject.parseObjectPropertyIntoArray (officeMockObject.ts:160:29)
    at officeMockObject.ts:168:22
    at Array.forEach (<anonymous>)
    at OfficeMockObject.parseObjectPropertyIntoArray (officeMockObject.ts:160:29)
    at OfficeMockObject.load (officeMockObject.ts:47:25)

**Comment by igor-ribeiiro** [comment]
Hi @tomprod, thanks for raising this issue, keep them coming when you find any!. 
Unfortunately, I didn't quite get to replicate your error. 
The code you posted didn't work right away, so I had to make a few modifications to it to make it run. After that, the code ran fine without throwing any errors.

This is the code I ended up testing:
```
import * as assert from "assert";
import "mocha";
import { OfficeMockObject } from "office-addin-mock";

/* global console, describe, global, it, require, Word */

let spyVariable = null;

const WordFields = [
  {
    text: "A",
    insertText: (text) => {
      spyVariable = text;
    },
  },
];

const MockData = {
  context: {
    document: {
      body: {
        search: function () {
          return {
            items: WordFields,
          };
        },
      },
    },
    items: WordFields,
    InsertLocation: {
      replace: {},
    },
  },
  run: async function (callback) {
    await callback(this.context);
  },
};

describe("Excel", function () {
  it("Run", async function () {
    const contextMock = new OfficeMockObject(MockData) as any;
    global.Word = contextMock;

    await Word.run(async (context: any) => {
      const foundWords = context.document.body.search("pattern", {
        matchWildcards: true,
        matchCase: false,
      }).items;
      foundWords[0].insertText("test"); 
    });
  });
});
```

Could you please check this code I've sent to see if you found any problem with it? It seems to be what you intended to do.
Also, a new version of the package was just published to fix some problems with arrays. If you can also test against this new latest version that would be great.

**Comment by tomprod** [comment]
Hi, thank you very much it now works with 1.0.3
