### ISSUE TITLE
Office-Addin-Dev-Settings not forcing IE on BetaChannel Word

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/Office-Addin-Scripts#568]
# Expected behavior

As per the documentation here (https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing), I expected that when using the BetaChannel Word and running `npx office-addin-dev-settings webview manifest.xml ie` that after reloading Word (or restarting Windows), that my add-in would be loaded in an IE browser.

# Current behavior

In lieu of being run in IE, the add-in is run in Microsoft Edge, and when I delete Edge Webview2 from my machine, my add-in runs in Edge Legacy. It ignores the registry key (confirmed it is there, and my add-in ID is correct) and just uses the latest version of Edge.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Office using ODT with the instructions here (Beta Channel): https://insider.office.com/en-us/business/deploy/windows/office-deployment-tool
2. Run `npx office-addin-dev-settings webview manifest.xml ie`
3. Restart Windows (or not)
4. Check the runtime inside the running add-in

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 Pro (10.0.19043)
* Node version: 16.13.1
* Office version: 2112 (Build 14718.20000) - Beta Channel

![Screen Shot 2021-12-04 at 23 42 26](https://user-images.githubusercontent.com/3823045/144733935-d389a20b-de58-4791-a676-01939f4c26a9.png)

![regedit](https://user-images.githubusercontent.com/3823045/144734031-1f617a78-d6a1-4965-af38-916588c74950.png)

Note: My workaround was to install a version of Word that is only IE11 (as per the above website).

**Comment by millerds** [comment]
What are you specifically doing to reload word?

**Comment by sureshjoshi** [comment]
@millerds Quitting and re-opening Word, and/or full OS restart

**Comment by millerds** [comment]
It sounds like you are trying to use Word generally instead for Office Add-in development.  The tool is designed for development scenarios where you have an add-in project you are trying to sideload and test.  It sets the webview for a specific add-in (generally the project you are sideload) and not add-ins in general.

**Comment by sureshjoshi** [comment]
That's the exact scenario I'm in. 

I'm building an add-in, trying to test it out in IE11 - as per the documentation, and the CLI version does not select IE11 for the add-in I'm developing.

**Comment by millerds** [comment]
How are you loading the add-in in Word?  What version of office-addin-debuggin and office-addin-scripts packages do you have installed?

When I follow the instructions with current project it works so there is something different about our environments or how we're going about our configuration and launching.

**Comment by millerds** [comment]
Are you still looking at this @sureshjoshi?

**Comment by sureshjoshi** [comment]
Nah, I've put the kibosh on IE11 - it was only needed because AppSource required IE11 testing.
