### ISSUE TITLE
office-addin-debugging | platform not supported: darwin

### ISSUE THREAD

**Issue by sankshit** [OfficeDev/Office-Addin-Scripts#571]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

The debugging should start on dev-server

# Current behavior

![image](https://user-images.githubusercontent.com/88471294/145361262-ff3ad66b-f592-4b4d-a8bc-d3c865a8974c.png)

## Steps to Reproduce
- Update to latest macOs (Monterey)
- Start the server
- It fails

## Context

* Operating System: macOs  12.0.1
* Node version: v14.17.4

**Comment by sankshit** [comment]
Got the resolution. Thanks

**Comment by ryanwhitemedia** [comment]
I am still getting this error.

**Comment by ryanwhitemedia** [comment]
I am getting this error trying to run `npx office-addin-dev-settings webview manifest.xml ie`
@millerds

**Comment by millerds** [comment]
@ryanwhitemedia that case is intentional . . . the "webview" command is windows only (uses the windows registry).

**Comment by yogasanas** [comment]
I am getting the error when trying to enable logging on a mac. 
```
❯ npx office-addin-dev-settings runtime-log                                                                                                                     │
Error: Platform not supported: darwin.
```
