### ISSUE TITLE
Unable to start debugging & office_addin_manifest_1.readManifestFile is not a function

### ISSUE THREAD

**Issue by dheerajbalmuri** [OfficeDev/Office-Addin-Scripts#575]
Getting the following error when running Office Js(Add-In)the project.

below is the data from console
*****************************************************************************
npm run start
Debugger attached.

> office-addin-taskpane-react@0.0.1 start E:\office-addins-msal-master
> office-addin-debugging start manifest.xml

Debugger attached.
Debugging is being started...
App type: desktop
Error: Unable to start debugging.
office-addin-debugging: office_addin_manifest_1.readManifestFile is not a function
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
*********************************************************************************************

**Comment by millerds** [comment]
What version of office-addin-debugging and office-addin-manifest is being imported in your project?  Can you run 'npm install' and try again?

**Comment by nikhilism15** [comment]
I'm having the same issue. It's so weird. The same project works on a different laptop (with Win 10) and in my current laptop I am able to run a sample add-in on excel, so I'm not sure what's going wrong.

**Comment by millerds** [comment]
The current version of Office-Addin-Debugging is 4.3.7 (https://www.npmjs.com/package/office-addin-debugging).  I would suggest updating to that.

**Comment by dheerajbalmuri** [comment]
@millerds  i did run npm i for a number of times.

**Comment by dheerajbalmuri** [comment]
nnnnnnnnnnnnnn

**Comment by dheerajbalmuri** [comment]
accidentally closed

**Comment by millerds** [comment]
Have you tried the newest version of the package?

**Comment by nikhilism15** [comment]
> Have you tried the newest version of the package?

Yes. Installed the latest version both locally and globally.

I deleted and reinstalled node_modules and deleted npm cache and reinstalled nodejs and everything else I could think of.

**Comment by millerds** [comment]
Between your last comment and  looking at your output again my guess is that there is something else going on beside just starting the project.

- You shouldn't need to install any of the Office-Addin-* projects globally, that are intended for use locally in a project
- Running 'npm start' shouldn't be emitting a project directory path as part of for the command ouput for the project (office-addin-taskpane-react@0.0.1 start **E:\office-addins-msal-master**)
- There are extra comments about "Debugger attached." in the output, even before the project debugging being started output.

If I create a project using 'yo office' for excel using react called "test", switch to the new "test" project directory after it's been created, and run npm start, then everything starts up as it should.

Can you tell us more about the project you created and the environment you are working in.

**Comment by nakawankuma** [comment]
We appear this same issue.
I have the my project.
I ran git clone & npm install on the new machine.
I see "TypeError: manifest.readManifestFile is not a function".
but I dont changed this package.json and manifest.xml.

I tried Yeoman install and create new addin that it is run.
I saw not error.

I tried my project node_modules override new addin node_module folder.
i saw 
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto

> office-addin-taskpane-react@0.0.1 start  
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
? Allow localhost loopback for Microsoft Edge WebView? No
Enabled debugging for add-in 05c2e1c9-3e1d-406e-9a91-e9ac64854143.
Starting the dev server... (webpack-dev-server --mode development)
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.        
Error: Sideload to the OneNote app is not supported.


It's changed error patern that depends on dev-server

I think so its error deneds on dev-server or current directory.
-----------------
oridinal dependncies part of package.json

"dependencies": {
    "@types/jest": "^24.0.20",
    "axios": "^0.19.0",
    "core-js": "^3.3.4",
    "cropperjs": "^1.5.6",
    "es6-promise": "^4.2.8",
    "font-awesome5": "^1.0.5",
    "immutable": "^4.0.0-rc.12",
    "jimp": "^0.8.5",
    "js-base64": "^2.5.1",
    "localforage": "^1.7.3",
    "moment": "^2.24.0",
    "msal": "^1.1.3",
    "office-ui-fabric-react": "^7.55.1",
    "react": "^16.11.0",
    "react-cropper": "^1.3.0",
    "react-dom": "^16.11.0",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-persist": "^5.10.0",
    "sharp": "^0.23.1",
    "uuid": "^3.3.3",
    "piexifjs": "^1.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@fortawesome/fontawesome-free": "^5.11.2",
    "@types/es6-collections": "^0.5.29",
    "@types/es6-promise": "^3.3.0",
    "@types/office-js": "^1.0.47",
    "@types/office-runtime": "^1.0.8",
    "@types/react": "^16.9.11",
    "@types/react-dom": "^16.9.3",
    "@types/react-hot-loader": "^4.1.0",
    "@types/webpack": "^4.39.5",
    "@types/webpack-dev-server": "^3.4.0",
    "@typescript-eslint/eslint-plugin": "^2.5.0",
    "@typescript-eslint/parser": "^2.5.0",
    "@typescript-eslint/typescript-estree": "^2.5.0",
    "babel-loader": "^8.0.6",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^5.0.4",
    "css-loader": "^3.2.0",
    "enzyme": "^3.10.0",
    "eslint": "^6.6.0",
    "eslint-plugin-node": "^9.2.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-standard": "^4.0.1",
    "extract-text-webpack-plugin": "4.0.0-beta.0",
    "file-loader": "^4.2.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^24.9.0",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "office-addin-debugging": "^2.4.4",
    "office-addin-dev-certs": "^1.4.11",
    "office-toolbox": "^0.2.1",
    "postcss-loader": "3.0.0",
    "react-hot-loader": "^4.12.15",
    "source-map-loader": "^0.2.4",
    "style-loader": "^0.23.1",
    "ts-jest": "^24.1.0",
    "ts-loader": "^6.2.1",
    "typescript": "^3.6.4",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.9",
    "webpack-dev-server": "^3.9.0"
  },

**Comment by millerds** [comment]
@nakawankuma if you reply "no" to the request "Allow localhost loopback for Microsoft Edge WebView?" then debugging won't work . . . it needs to be allowed in order for the localhost to be able to run the add-in and debugger service.

**Comment by nakawankuma** [comment]
@millerds 
Thank you for reply comment.
![image](https://user-images.githubusercontent.com/25449408/153791446-d2c77eab-9c58-4484-8591-c6d02b35604c.png)
I tried to run no debugging mode. but I received same answer. 

> Debugging is being started...
> App type: desktop
> ? Allow localhost loopback for Microsoft Edge WebView? No
> Enabled debugging for add-in 05c2e1c9-3e1d-406e-9a91-e9ac64854143.
> Starting the dev server... (webpack-dev-server --mode development)
> Sideloading the Office Add-in...
> Error: Unable to start debugging.
> Error: Unable to sideload the Office Add-in. 
> Error: Sideload to the OneNote app is not supported.

I dont ran debugging mode. but there is messsage.

**Comment by millerds** [comment]
Replying 'yes' to that question is required for any running the adding locally (attaching to the debugger or not) which is what our commands are trying to do.

**Comment by akrantz** [comment]
The other part of that message also indicates that "Sideload to the OneNote app is not supported". Are you trying to debug the add-in running in OneNote desktop or web?

 Use "npm run start:web" to enable debugging for the add-in and start the web server but not sideload. This will also work for desktop. You'll probably find it easiest to use the browser dev tools to debug. 
 
 Also, is there some reason to not allow localhost loopback?

**Comment by millerds** [comment]
@dheerajbalmuri @nikhilism15 @nakawankuma are you still having problems using current version of the scripts packages and 'yo office'?

**Comment by millerds** [comment]
Closing.  If there are any further problems, please re-open.
