### ISSUE TITLE
Unable to send feedbacks

### ISSUE THREAD

**Issue by webartoli** [OfficeDev/Office-Addin-Scripts#576]
# Expected behavior

I want to subbmit feature request/feedback to influence roadmap.

# Current behavior

Link provided by issue template is broken.

> Please provide information about the failure. What is the current behavior? If it is not a bug, please add it to [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.

**Comment by millerds** [comment]
User voice was retired in favor of another platform.  This is a link that was not updated (thanks for pointing that out).  I am in the process of correcting that. 

Here is where you can submit requests: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
