### ISSUE TITLE
Unable to sideload via devcontainer

### ISSUE THREAD

**Issue by webartoli** [OfficeDev/Office-Addin-Scripts#577]
# Prerequisites

Please answer the following questions before submitting an issue. 

- [X] I am running the latest version of Node and the tools
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Expected behavior

Sideload support from devcontainer.

# Current behavior

`Error: Platform not supported: linux.`

Please note that I've opened this feature request as bug because https://github.com/OfficeDev/Office-Addin-Scripts/issues/576

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. generate office via yo
2. create a node devcontainer
3. try to sideload your addin via package.json template or manually

The minimal command to sideload manually is:
`yarn office-addin-dev-settings sideload manifest.xml`

## Context

In this case context is WSL: host info are not relevant. By the way I have tried on:
- MacOS Monterey 21.1
- Windows 10
- Windows 11

With :
* Node version: Node latest LTS (v16.13.1)
* Office version: Office 365 - Montly update

**Comment by millerds** [comment]
Here is where you can submit feature requests: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
