### ISSUE TITLE
office-addin-dev-certs: keeps adding new certs on mac

### ISSUE THREAD

**Issue by mathiastornblom** [OfficeDev/Office-Addin-Scripts#579]
office-addin-dev-certs@1.7.4 works @1.7.5 and 1.7.6 tries to install CA cert every time and webpack@5.65.0 fails to start.

**Comment by mathiastornblom** [comment]
I started a new project with 'yo' and could easily do 'npm start'. it creates the certs if they don't exists and if they do and are valid it just passes through. from package.json:

"office-addin-cli": "^1.3.0",
"office-addin-debugging": "^4.3.0",
"office-addin-dev-certs": "^1.7.0",
"office-addin-lint": "^1.4.0",
"office-addin-manifest": "^1.7.0",
"office-addin-prettier-config": "^1.1.0",
"eslint-plugin-office-addins": "^1.1.0",

then upgraded all packages to these versions (latest)
 office-addin-cli                ^1.3.0  →    ^1.3.4     
 office-addin-debugging          ^4.3.0  →    ^4.3.7     
 office-addin-dev-certs          ^1.7.0  →    ^1.7.6     
 office-addin-lint               ^1.4.0  →    ^1.4.5     
 office-addin-manifest           ^1.7.0  →    ^1.7.6     
 office-addin-prettier-config    ^1.1.0  →    ^1.1.3 
eslint-plugin-office-addins     ^1.1.0  →    ^1.1.4 

then it creates the CA cert and wants to install it every time I run 'npm start' and the webpack server won't start unless I do a 'npm run dev-server'
I traced and figured out that it all came down to one package by having the original version and step by step upgrading office-addin-dev-certs package only. 1.7.5 and 1.7.6 versions of office-addin-dev-certs brakes it. running 'npx office-addin-dev-certs verify' on the different versions works until 1.7.4 after that it says I have to trust the cert

1.7.0 example
mathiast@MBPsomtrMathias Test % npx office-addin-dev-certs verify
Debugger listening on ws://127.0.0.1:64403/20c6a376-7f27-4791-a9c4-ed82f265ab8f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:64409/15854ca3-7e5a-4a5d-85e1-b8ac4543b8d0
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
You have trusted access to https://localhost.
Certificate: /Users/mathiast/.office-addin-dev-certs/localhost.crt
Key: /Users/mathiast/.office-addin-dev-certs/localhost.key

1.7.5 example
mathiast@MBPsomtrMathias Test % npx office-addin-dev-certs verify       
Debugger listening on ws://127.0.0.1:64452/e81a2b05-42bb-4573-a586-17e061fd6897
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:64458/9dfca03f-3c51-4007-b6d6-4fb060125122
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
You need to install certificates for trusted access to https://localhost.

**Comment by millerds** [comment]
Thanks for the detailed investigation.  I'm not experiencing the same thing so if you don't mind I'd like to ask you to help investigate by running some commands on your machine and giving me the output.

To provide some context, starting with 1.7.4 the sh scripts used to verify and uninstall certs was adjusted to better clean up expired keychain entries that were getting left behind and sometime getting used by the dev server (which would then fail because of an expired cert).  I need to see what is returned by these scripts to figure out where the disconnect is (could also be with the cert file).

Can you provide the output of these commands run in the terminal:

- security find-certificate -a -c "Developer CA for Microsoft Office Add-ins" -p
- security find-certificate -c "Developer CA for Microsoft Office Add-ins" -a -Z | grep SHA-1 | awk '{ print $NF }'

Can you also tell me the contents of the ".office-addin-dev-certs" folder in your user's home directory?

**Comment by mathiastornblom** [comment]
mathiast@MBPsomtrMathias .office-addin-dev-certs % security find-certificate -a -c "Developer CA for Microsoft Office Add-ins" -p
-----BEGIN CERTIFICATE-----
MIIDzDCCArSgAwIBAgIFNjM2MDAwDQYJKoZIhvcNAQELBQAwgZQxMjAwBgNVBAMT
KURldmVsb3BlciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMQswCQYD
VQQGEwJVUzELMAkGA1UECBMCV0ExEDAOBgNVBAcTB1JlZG1vbmQxMjAwBgNVBAoT
KURldmVsb3BlciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMB4XDTIy
MDEwNjIzMzM0MloXDTIyMDIwNTIzMzM0MlowgZQxMjAwBgNVBAMTKURldmVsb3Bl
ciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMQswCQYDVQQGEwJVUzEL
MAkGA1UECBMCV0ExEDAOBgNVBAcTB1JlZG1vbmQxMjAwBgNVBAoTKURldmVsb3Bl
ciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAxtLrbI6RawEfxOYitxh3W1krFcbmJizzqY+pDl+/
XTFwl5VC7ksWM4wg2oYrFGk2SqsSJAW831orEkz0aDzsIwBH22H0qu8/MIghsxGW
URlr9GinIOtwbjssuYYA9TNpIuMTvzwmY0nxMujoHZyENQ/hYe7/c2TSava6J8fe
KQSPmTNQbtGUOmLvUoI107W0y1448NvG1xha818FtPrZGKf5GdUNAXJ7NS1gnf9B
EDCWhwCRDJg72KXH8Q4t8HIa+OXX8VAo7DRiTZI/bv7KMkosEHpe490koi+2dYNA
ICK7itmGTC4goJiEvBThKg3/X/XYK9OON73Fkxqk8mAgzQIDAQABoyMwITAPBgNV
HRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDANBgkqhkiG9w0BAQsFAAOCAQEA
wJKXWnHZxJ5XjBpYo+GW/Trnus5zMP9cXLlE8roe2Yar5F3GeM5Wrf0bkKTpmqlX
/X1Q99MQzqKRtTjIBlaSr5JVjXey7XPjSYb4eSFsKEAqKrC96u+Un7LrOB7Fiuf3
PLjM2dEEhxWPK/A35bBhWdmCilnF1B6P2KMVZBCBw0VGtvTHhZ897ejuVN0fNvAf
F9Wl15bUQsjc0PyVWdvyjaaTxkSqF9M2qGrORE+auGEKuRb/zBqGlS98+SDqaUGL
qUn4BGHdEMzJGpvWgbCCxXwawXqOzSjMg9V9TFS23Dsr8y/8Ktq2+EJE9aimX3P8
KhkuHBL13N0F1RU0s3F40g==
-----END CERTIFICATE-----
mathiast@MBPsomtrMathias .office-addin-dev-certs % security find-certificate -c "Developer CA for Microsoft Office Add-ins" -a -Z | grep SHA-1 | awk '{ print $NF }'
4726A23C207EAFEEFE4583B6CB561680221D64C9
mathiast@MBPsomtrMathias .office-addin-dev-certs % ls   
ca.crt		localhost.crt	localhost.key
mathiast@MBPsomtrMathias .office-addin-dev-certs %

**Comment by millerds** [comment]
Thanks for all of that, Now please run 'security find-certificate -a -c "Developer CA for Microsoft Office Add-ins" -p | openssl x509 -checkend 86400' and let me know the output.

**Comment by mathiastornblom** [comment]
mathiast@MBPsomtrMathias .office-addin-dev-certs % security find-certificate -a -c "Developer CA for Microsoft Office Add-ins" -p | openssl x509 -checkend 86400 
Certificate will not expire
mathiast@MBPsomtrMathias .office-addin-dev-certs %

**Comment by millerds** [comment]
Next I need you to be in the project folder setup with the 1.7.6 version of the package installed and run this command

sh ./node_modules/office-addin-dev-certs/scripts/verify.sh "Developer CA for Microsoft Office Add-ins"

**Comment by mathiastornblom** [comment]
mathiast@MBPsomtrMathias Fortnox Order % sh ./node_modules/office-addin-dev-certs/scripts/verify.sh "Developer CA for Microsoft Office Add-ins"
-----BEGIN CERTIFICATE-----
MIIDzDCCArSgAwIBAgIFNjM2MDAwDQYJKoZIhvcNAQELBQAwgZQxMjAwBgNVBAMT
KURldmVsb3BlciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMQswCQYD
VQQGEwJVUzELMAkGA1UECBMCV0ExEDAOBgNVBAcTB1JlZG1vbmQxMjAwBgNVBAoT
KURldmVsb3BlciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMB4XDTIy
MDEwNjIzMzM0MloXDTIyMDIwNTIzMzM0MlowgZQxMjAwBgNVBAMTKURldmVsb3Bl
ciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMQswCQYDVQQGEwJVUzEL
MAkGA1UECBMCV0ExEDAOBgNVBAcTB1JlZG1vbmQxMjAwBgNVBAoTKURldmVsb3Bl
ciBDQSBmb3IgTWljcm9zb2Z0IE9mZmljZSBBZGQtaW5zMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAxtLrbI6RawEfxOYitxh3W1krFcbmJizzqY+pDl+/
XTFwl5VC7ksWM4wg2oYrFGk2SqsSJAW831orEkz0aDzsIwBH22H0qu8/MIghsxGW
URlr9GinIOtwbjssuYYA9TNpIuMTvzwmY0nxMujoHZyENQ/hYe7/c2TSava6J8fe
KQSPmTNQbtGUOmLvUoI107W0y1448NvG1xha818FtPrZGKf5GdUNAXJ7NS1gnf9B
EDCWhwCRDJg72KXH8Q4t8HIa+OXX8VAo7DRiTZI/bv7KMkosEHpe490koi+2dYNA
ICK7itmGTC4goJiEvBThKg3/X/XYK9OON73Fkxqk8mAgzQIDAQABoyMwITAPBgNV
HRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDANBgkqhkiG9w0BAQsFAAOCAQEA
wJKXWnHZxJ5XjBpYo+GW/Trnus5zMP9cXLlE8roe2Yar5F3GeM5Wrf0bkKTpmqlX
/X1Q99MQzqKRtTjIBlaSr5JVjXey7XPjSYb4eSFsKEAqKrC96u+Un7LrOB7Fiuf3
PLjM2dEEhxWPK/A35bBhWdmCilnF1B6P2KMVZBCBw0VGtvTHhZ897ejuVN0fNvAf
F9Wl15bUQsjc0PyVWdvyjaaTxkSqF9M2qGrORE+auGEKuRb/zBqGlS98+SDqaUGL
qUn4BGHdEMzJGpvWgbCCxXwawXqOzSjMg9V9TFS23Dsr8y/8Ktq2+EJE9aimX3P8
KhkuHBL13N0F1RU0s3F40g==
-----END CERTIFICATE-----
mathiast@MBPsomtrMathias Fortnox Order %

**Comment by millerds** [comment]
Hmm . . . so the keychain entry is being found and validated as still good.  Which leads me to suspect something happening when the cert files are being observed.  Unfortunately I don't have a good way of testing that without debugging.  You could run "npx office-addin-dev-certs uninstall" (or just delet the .office-addin-dev-certs folder) to try and clean out the cert and setup a new one and that should get you unblocked (I'll have to keep trying to find the bug seperatly).

**Comment by mathiastornblom** [comment]
I uninstalled the office-addin-dev-certs. deleted the .office-addin-dev-certs folder. then installed office-addin-dev-certs again. I get the prompt. is install the ca and trusts the 127.0.0.1 cert but the dev server does not start.

mathiast@MBPsomtrMathias Fortnox Order % npm start
Debugger listening on ws://127.0.0.1:62984/c08ea79f-56b7-4745-8f85-fd17cb4c6a7a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> Fortnox-Order@1.0.0 start
> office-addin-debugging start manifest.xml

Debugger listening on ws://127.0.0.1:62989/f9d4254d-bc8e-42aa-bfe6-d15a712ac5c3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugging is being started...
App type: desktop
The developer certificates have been generated in /Users/mathiast/.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Password:
Sorry, try again.
Password:
You now have trusted access to https://localhost.
Certificate: /Users/mathiast/.office-addin-dev-certs/localhost.crt
Key: /Users/mathiast/.office-addin-dev-certs/localhost.key
Starting the dev server... (webpack serve --mode development)
Unable to start the dev server. Error: The dev server is not running on port 3000.
Sideloading the Office Add-in...
Debugging started.
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

and it repeats the password question on next start of 'npm start' 
uninstalling office-addin-dev-certs and then install it with office-addin-dev-certs@1.7.4 and it works as it should

**Comment by millerds** [comment]
There's got to be an exception that is getting swallowed that I'm not seeing on my end.
After removing the folder and trying v1.7.6 do you see the folder getting created again with the cert files?
What version of Mac OS are you running on?

**Comment by mathiastornblom** [comment]
The folder is recreated every time the folder is deleted. the CA Cert is installed every time. My OS is OsX 12.2.

**Comment by millerds** [comment]
Sorry I had to step away from this for a while.  Are you able to repro this with current versions of office-addin-dev-certs?

**Comment by jeffwu85182** [comment]
I also face this problem in version 1.5.5, but it's working fine and not generating every time after upgrading to version 1.7.10.
