### ISSUE TITLE
ESLint unexpected behavior with Enums on no-unused-vars rule

### ISSUE THREAD

**Issue by azuken** [OfficeDev/Office-Addin-Scripts#580]
# Expected behavior

Use enum in project without `no-unused-vars` "false" ESLint error.

# Current behavior

Enum declaration with React / TypeScript Office Add-in based project results with `no-unused-vars` even if this enum is used. 

See this issue which describe the problem with more details, and the resolution : https://github.com/typescript-eslint/typescript-eslint/issues/1197.

Since it's not possible to override `office-addin-lint` configuration, can you please provide a fix for eslint plugin(s)?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. declare an enum and use it

```ts
enum Foo {
  Bar
}

console.log(Foo.Bar);

```
2. execute `office-addin-lint check` and see reported error :

`'Bar' is defined but never used  no-unused-vars`

## Context

Creation of Office Add-in Outlook project

* Operating System: MacOS
* Node version: 16
* Office version: 2019
* Tool version: 1.4.5

**Comment by akrantz** [comment]
You should be able to override eslint config settings locally. Is a newer version of the `typescript-eslint` package needed, or is there some other sort of config change required? It's wasn't clear from the issue referenced.

**Comment by millerds** [comment]
You are correct that we are missing a line in our lint cli's eslintrc.json file that would enable this (and a bunch of other typescript rules) and it looks like this was the intent, but not quite right.  

We can fix that, but you can also alter the rules that are used locally using the eslint-disable code comments to remove the warnings (like "// eslint-disable-line no-unused-vars" at the end of a single line).  This will affect the cli check and the live linting that goes on in VS Code (note that if you update the eslintrc.json file in your project to use the typescript plugin it will affect the live linting, but not the cli).

**Comment by azuken** [comment]
@akrantz I can have my own settings locally for ESLint indeed, but `office-addin-lin` CLI will continue to fail.
For what is needed, it's more like adding / updating CLI config file rules with new ESLint ones more than updating dependencies.

@millerds This is what I've done for now, using disable comments, but it's more a workaround than a solution.

**Comment by igor-ribeiiro** [comment]
This should be fixed now in the last update we make. Please update your package to the latest versions to get `office-addin-lint` correctly working for Enums.

**Comment by azuken** [comment]
It's working, thank you for your quick fix !
