### ISSUE TITLE
Content blocked with fresh Windows 11 install

### ISSUE THREAD

**Issue by svickers** [OfficeDev/Office-Addin-Scripts#599]
# Expected behavior

New laptop with windows 11 and I can't get our existing add-in to load or a fresh one created with yeoman. 

# Current behavior

When running `npm run dev-server` it says the certificate is installed but when opening the task pane in excel the content is still blocked as unsecure.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Follow instructions from [quickstart guide](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
2. Open taskpane when Excel loads
3. Observe error message: The content is blocked because it isn't signed by a valid security certificate.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11
* Node version: 16.13.2
* Office version: 2112
* Tool version: 4.3.7

## Failure Logs
```
> office-addin-taskpane-react@0.0.1 dev-server
> webpack-dev-server --mode development

The developer certificates have been generated in C:\Users\ScottVickers\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
You now have trusted access to https://localhost.

Certificate: C:\Users\ScottVickers\.office-addin-dev-certs\localhost.crt
Key: C:\Users\ScottVickers\.office-addin-dev-certs\localhost.key
(node:9984) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wds｣: Project is running at https://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\ScottVickers\dev\Excelsior
i ｢wdm｣: Hash: d6d121765740f29d2572
Version: webpack 4.46.0
Time: 9870ms
Built at: 01/25/2022 5:36:06 PM
```

<img width="272" alt="Screenshot 2022-01-25 174758" src="https://user-images.githubusercontent.com/105884/151089651-7ca69986-8e5a-467d-9492-e298a930c1ad.png">

**Comment by igor-ribeiiro** [comment]
Hello @svickers,

I don't quite know why you are facing this issue. 
I just tried running a fresh adding generate by yo office on my machine and got the task pane to load.

As this seems to be a certificate problem, could you please try running the following two commands?
`npx office-addin-dev-certs verify` and `npx office-addin-dev-certs install`?

Please, let me know if your adding (or a fresh one) open after those commands

**Comment by svickers** [comment]
Hi @igor-ribeiiro 

When initially running the verify command this was the output:

```
You need to install certificates for trusted access to https://localhost.
```

Then I ran the install command

```
The developer certificates have been generated in C:\Users\ScottVickers\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
You now have trusted access to https://localhost.
Certificate: C:\Users\ScottVickers\.office-addin-dev-certs\localhost.crt
Key: C:\Users\ScottVickers\.office-addin-dev-certs\localhost.key
```

After that when running the verify command it gives the same error about needing to be installed.

I had a similar problem when set up a project with iisexpress in VS2022 and running `dotnet dev-certs https --trust` wasn't working properly.  To resolve I had to open up certmgr, change the view option to show physical addresses, then drag the localhost cert out of Personal/Registry/Certificates and into Trusted Root Certification Authorities/Local Computer/ Certificates.  

For this I took the ca.crt and localhost.crt files from the /.office-addin-dev-certs folder and imported them into my Trusted Root Certificate Authorities collection and now the verification works and add-in gets served in Excel.  Not sure if there is some group policy in place or a win11 default that is preventing the certs from being installed properly or what, gonna be a pain to re-import each time it expires.  Not sure where else to begin looking.

**Comment by akrantz** [comment]
@svickers You mentioned that `dotnet dev-certs` command also had a problem. It sounds more like the certificates aren't working when in your personal user registry. Any idea why? 

There is an option on `office-addin-dev-certs install` to use the machine registry instead of personal. Add `--machine`. This requires running in an Administrator command prompt.

**Comment by igor-ribeiiro** [comment]
@svickers Did you manage to try @akrantz advice? It could help you fix these certificate problems.
I will close the issue if it is fixed

**Comment by igor-ribeiiro** [comment]
I will be closing the issue as there was no response.
