### ISSUE TITLE
npm run configure-sso results in Error: Unable to set tenant reply urls

### ISSUE THREAD

**Issue by cldellow** [OfficeDev/Office-Addin-Scripts#639]
# Expected behavior

I've never done this successfully, but I expected these steps to result in a success, not an error message.

I followed the instructions at https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator to create an add-in with SSO support:

```
yo office # Picked SSO, Excel, TypeScript
npm run configure-sso
```

I expected a clean exit.

# Current behavior

`npm run configure-sso` popped a browser, I logged in to my Azure tenant. Then the output from `configure-sso` showed:

```
C:\Users\cldel\test\My Office Add-in>npm run configure-sso

> office-addin-taskpane-sso@0.0.0 configure-sso
> office-addin-sso configure manifest.xml

Opening browser for authentication to Azure. Enter valid Azure credentials
Login was successful!
Registering new application in Azure
Application was successfully registered with Azure
Setting identifierUri
    Attempt 1
Itendifier Set
Setting signin audience
    Attempt 1
Sign In Audience Set
Granting admin consent
    Attempt 1
Consent granted
C:\Users\cldel\test\My Office Add-in\node_modules\office-addin-sso\lib\configure.js:289
            throw new Error(errorMessage);
                  ^

Error: Unable to set tenant reply urls.
ERROR: Method Not Allowed({"error":{"code":"Request_BadRequest","message":"Specified HTTP method is not allowed for the request target.","innerError":{"date":"2022-05-12T20:17:38","request-id":"80db34de-a414-476f-b447-cd6b00d9ff6e","client-request-id":"80db34de-a414-476f-b447-cd6b00d9ff6e"}}})

    at Object.<anonymous> (C:\Users\cldel\test\My Office Add-in\node_modules\office-addin-sso\lib\configure.js:289:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\cldel\test\My Office Add-in\node_modules\office-addin-sso\lib\configure.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

## Steps to Reproduce

See expected behaviour.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10  Home, 21H2 build 19044.1706
* Node version: v16.15.0
* Office version: 2204 (Build 15128.20224 Click-to-Run)
* Tool version:  office-addin-sso@1.2.8

## Failure Logs

See current behaviour section.

**Comment by shillyshallysxy** [comment]
I've got the same problem.

**Comment by millerds** [comment]
Does the tenant you are using have SharePoint on it?  What permissions does the user you are logging into the tenant have?

BTW . . . there is a sso specific quick start at https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart

**Comment by cldellow** [comment]
The user I'm logging in with is a Global Administrator.

Sorry, I'm not very experienced with the Microsoft stack. How do I know if my tenant has SharePoint? The tenant was freshly created for the purpose of building this integration, so unless I get SharePoint by default, I would guess the tenant did not have SharePoint.

For the short term, I ended up not using Office's SSO features -- instead, I manually pop an iframe to log the user into Microsoft's STS. I guess this sucks a bit for the user (since their Office identity can now diverge from their identity in my addin), but it allowed me to move forward.

**Comment by millerds** [comment]
What kind of tenant did you create (i.e. what license)?

**Comment by cldellow** [comment]
When I look at the Azure Active Directory blade in portal.azure.com, I see `License: Azure AD Free` -- is that what you are referring to?

**Comment by millerds** [comment]
I think you have an Azure tenant.  Can you try getting a M365 tenant?

https://developer.microsoft.com/en-us/microsoft-365/dev-program

**Comment by cldellow** [comment]
Unfortunately, since I've found a workaround, I don't have time to explore this further. If we decide to take another swing at doing Office SSO, I'll give that a try. Thanks for your pointers!

**Comment by vazromju** [comment]
Hello,
I have the same problem and I am unable to continue the process
Could you please re-open the issue?

**Comment by millerds** [comment]
@vazromju can you tell me what kind of tenant you are authenticating to when prompted in the browser?

**Comment by vazromju** [comment]
thank you @millerds 

I have just solved it adding a M365 tenant.
The problem was I tried to execute the script `npm run configure-sso` and login into Azure with the demo admin account (admin@1234.onmicrosoft.com) so it fails.
Login-in with my real account does the trick

**Comment by rifat-manjur-enosis** [comment]
Can you please tell me the difference between demo account and real account? Can you explain the steps in details how you have added M365 tenant? I am facing the same problem. I am using free developer admin account.

**Comment by coreprocess** [comment]
I just leave this here in case it helps: https://github.com/OfficeDev/generator-office/issues/749#issuecomment-1442424374
