### ISSUE TITLE
How can I set the numberformatCategory for Range Cell

### ISSUE THREAD

**Issue by LiuXiao617111** [OfficeDev/Office-Addin-Scripts#642]
![image](https://user-images.githubusercontent.com/8858358/170168606-b3343400-14b1-437d-9b70-0b3f80d3250f.png)
How can I set this function like screenshot by JS API. 
the numberformatCategory  is read only so I can not set it.

**Comment by millerds** [comment]
Are you looking for Range.numberFormat maybe?  https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-numberformat-member
