### ISSUE TITLE
office-addin-dev-cerrts cli has dos ending \r

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/Office-Addin-Scripts#644]
When I run `office-add-dev-certs install` i get the error message: 
`/usr/bin/env: ‘node\r’: No such file or directory` which is caused by \r endings. I use linux. The error is cause by the chebang in node_modules/.bin/office-addin-dev-certs. A temp fix is: 
`cat node_modules/.bin/office-addin-dev-certs | tr -d '\r'> node_modules/.bin/office-addin-dev-certs` 

I am on v 1.7.10

**Comment by millerds** [comment]
Hmm . . . I don't understand why this is.  The tsconfg.json settings say to output the js files with just the LF and not the CRLF even on windows machines.  I'm seeing this with the output of the build for this package.  I'm not sure how this gets change by the npm publish command.

**Comment by millerds** [comment]
Looks like most of the files were correctly done, but not all since not all are built ts files.

**Comment by JensMadsen** [comment]
@millerds without looking too much i think it is simply the https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-dev-certs/cli.js file that is committed with "wrong" endings

**Comment by hingew** [comment]
I got the same error with `office-addin-debugging start manifest.xml web` on linux.

**Comment by millerds** [comment]
Have this fixed . . .will be in the next version updated.

**Comment by millerds** [comment]
Updated version published.
