### ISSUE TITLE
office-addin-debugging stop manifest.xml does not properly stop the webpack dev server

### ISSUE THREAD

**Issue by Anthony-Breneliere** [OfficeDev/Office-Addin-Scripts#649]
# Issue

When I stop the debugging, we have to wait for an undefined amount of time before the webpack dev port is freed, allowing to launch debugging again.

net stop seems to kill a process, but does not stop properly the web server, to when I launch debugging again, the message is displayed:
```
The dev server is already running on port 3000.
```

And the addin cannot work because the webpack webserver is not launched with net start.

# Prerequisites

Generate an Angular server with
yo Office

# Expected behavior

```
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
? Allow localhost loopback for Microsoft Edge WebView? Yes
Enabled debugging for add-in 2debe8e3-f9d9-40cc-988e-5a45f7a96282.
Starting the dev server... (webpack serve --mode development)
The dev server is running on port 3000. Process id: 39876
Sideloading the Office Add-in...
Debugging started.
```

# Current behavior

```
office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
? Allow localhost loopback for Microsoft Edge WebView? Yes
Enabled debugging for add-in 2debe8e3-f9d9-40cc-988e-5a45f7a96282.
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Debugging started.
```

## Steps to Reproduce

Launch an administrator console, and go to the generated Angular project directory (that contains package.json)

1/ npm start
2/ npm stop

```
office-addin-debugging stop manifest.xml

Debugging is being stopped...
Stopped dev server. Process id: 39876
Debugging has been stopped.
```

3/ npm start

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11
* Node version: 14.17.1
* Office version: 2016
* Tool version: "office-addin-debugging": "^4.3.14"

**Comment by millerds** [comment]
This is actually something I have spent some time off and on looking into.  When checking for a running server the package is looking for port binding and while the main processes have been stopped (dev server and the office application) sometimes all of the bindings that were created take time to get fully cleaned up.  We have to consider how to clean these up without negative side effects.

**Comment by Anthony-Breneliere** [comment]
Maybe using another way for checking if the dev http server is online, and not just looking for the port binding ? Maybe a GET on https://localhost:3000/ (or other configured port) response check would be sufficient ?

**Comment by millerds** [comment]
Have to be careful that we don't re-setup a binding and get a response from something else left over that isn't wanted.  

Looks like it's the host (office) application in windows that is creating the extra bindings and when it is shut down (after opening a taskpane) there are some bindings that get reassigned to pid 0 and those take time to get cleaned up.  I'm going to make a fix to ignore binding assigned to pid 0 (idle process) on win32 as I think it's safe to ignore these.

**Comment by millerds** [comment]
This change has been checked in and published.  Try the udpated office-addin-debugging package.

**Comment by JanTrichter** [comment]
@millerds 
I have created a new outlook plugin with yeoman recently (a few days ago) and this issue still exists. the `package.json` says `"office-addin-debugging": "^4.3.14"` and when I checked the `package.json` inside `node_modules` it says `"version": "4.4.0"`.
