### ISSUE TITLE
Should mention needing the Beta Channel version of Word for CLI

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/Office-Addin-Scripts#650]
According to the office-addin-dev-settings documentation (https://www.npmjs.com/package/office-addin-dev-settings#webview), it's required to be in the Beta Channel for the CLI functionality to work.

There is no mention of the Beta Channel on this page. Unfortunately, as I wasn't able to get the CLI version to work regardless, I don't know whether Beta is actually required or not.

![Screen Shot 2021-12-05 at 00 29 40](https://user-images.githubusercontent.com/3823045/144734942-41869e6c-87fb-44f2-8d2a-676aa7a32a24.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b7b417-12e6-193f-6b89-37e088b31dbc
* Version Independent ID: df705bd2-5f2f-2c84-0519-fca9a3c45d71
* Content: [Internet Explorer 11 testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing#feedback)
* Content Source: [docs/testing/ie-11-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/ie-11-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by millerds** [comment]
It looks like Office clients will not respect the reg key setting created by the office-addin-dev-settings command in main M365 delivery channels.  I remember seeing this explained in a no so obvious place, but I can't recall (or find) where that was or what specific channels (File=>Account=>Update Channel) the setting is honored in.  We should get this cleared up and documented better.

**Comment by millerds** [comment]
I found one place it was mentioned in documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing.  This information should be explained in more places.

**Comment by Rick-Kirkham** [comment]
@sureshjoshi I'm not clear on what your issue is. The requirement for Beta is mentioned in the page where you raised this issue. Here is a screen shot. 
![image](https://user-images.githubusercontent.com/9088056/210465936-c19bbca0-127e-4a96-aad0-b720fdf4929e.png)

**Comment by sureshjoshi** [comment]
@Rick-Kirkham I think the issue is solved. When I raised it (Dec 2021), that mention wasn't in the docs - but it looks like it was added Oct 2022: https://github.com/OfficeDev/office-js-docs-pr/commit/b0794feaf581616305d4bcd5d5480a13a3b077ac

I'm guessing this can be closed now?
