### ISSUE TITLE
Use eslint-plugin-office-addins without prettier

### ISSUE THREAD

**Issue by jkscx** [OfficeDev/Office-Addin-Scripts#663]
# Prerequisites

Please answer the following questions before submitting an issue. 
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Question

Hello, is it possible to use eslint-plugin-office-addins without prettier and the styling suggestions? To be more precise, is it possible to just have the correctness/safety [rules from the eslint-plugin-office-addins](https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/eslint-plugin-office-addins/src/rules) without the general prettier styling rules? Like that it checks the addin for office related safety/correctness, but nor for style errors.

Currently, even after I have removed all references to prettier from the project and clean installed the eslint-plugin-office-addins package, it still uses the prettier rules (and gives errors as they clash with our company's code style). Do you know of an way to help?

# Steps to reproduce

1. Have an office addin project with the following dependencies:
 		"eslint-plugin-office-addins": "^2.1.0",
		"office-addin-lint": "^2.0.0",
		"office-addin-cli": "^1.3.5",

and an eslintrc.js file with the following options:
	overrides: [
		{
			plugins: [
				"office-addins",
			],
			extends: [
				"plugin:office-addins/recommended",
			],
		}

2. Apply own styling to code, for example use "string" instead of 'string'.

3. Run "office-addin-lint check" (or regular "eslint ./src --ext .ts")  and get "prettier/prettier" errors about code style...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version: 16
* Office version: N/A

**Comment by fra-smw** [comment]
Any news about this?

**Comment by parched** [comment]
You should be able to do this by removing the `extends: ["plugin:office-addins/recommended"]` and adding
```
      rules: {
        "office-addins/call-sync-after-load": "error",
        "office-addins/call-sync-before-read": "error",
        "office-addins/load-object-before-read": "error",
        "office-addins/no-context-sync-in-loop": "warn",
        "office-addins/no-empty-load": "warn",
        "office-addins/no-navigational-load": "warn",
        "office-addins/no-office-initialize": "warn",
        "office-addins/test-for-null-using-isNullObject": "error",
      },
```
from https://github.com/OfficeDev/Office-Addin-Scripts/blob/29096f4493ae4e71277a8b4aa079ddadf0ddccee/packages/eslint-plugin-office-addins/src/main.ts#L27-L34

Perhaps, there should be another config in that file that only enables the `office-addins` rules.

**Comment by millerds** [comment]
You should be able to override eslint setting using the .eslintrc.json file in the project.  By adding this to the config file you should be able to turn off prettier.

"rules": {
  "prettier/prettier": "off"
}
