### ISSUE TITLE
"npm run start:web" works for a while and exits, webpack is working in the background

### ISSUE THREAD

**Issue by piotrkochan** [OfficeDev/Office-Addin-Scripts#664]
# Expected behavior

The `npm run start:web` should run continuously and report compiling errors, webpack messages etc

# Current behavior

Process is running:

```
> office-addin-taskpane-react-js@0.0.1 start:web
> office-addin-debugging start manifest.xml web

Debugging is being started...
App type: web
Starting the dev server... (webpack serve --mode development)
The dev server is running on port 3000. Process id: 296727
Sideloading the Office Add-in...
Debugging started.
```

And quits after a few seconds. I can see that webpack is running in the background:

```
netstat -lp | grep 3000
tcp6       0      0 [::]:3000               [::]:*                  LISTEN      296728/webpack
```

I'm not really sure if it is a proper behaviour of this command. I'm assuming that process should remain in the terminal to be terminated later by the user.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:  Ubuntu 20.04.4 LTS
* Node version: v16.16.0
* Office version: web
* Tool version: 

````
"office-addin-cli": "^1.3.8",
"office-addin-debugging": "^4.3.14",
"office-addin-dev-certs": "^1.7.10",
"office-addin-lint": "^2.0.3",
"office-addin-manifest": "^1.8.1",
"office-addin-prettier-config": "^1.1.7"
```

## Failure Logs

none

**Comment by millerds** [comment]
The command spins up webpack separately and is not required to continue running in the terminal.  If you want to stop webpack you run the command 'npm run stop'
