### ISSUE TITLE
eslint-plugin-office-addins doesn't support typescript 4.5+

### ISSUE THREAD

**Issue by parched** [OfficeDev/Office-Addin-Scripts#665]
# Expected behavior

No errors

# Current behavior
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.    

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

=============
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Take one of the examples like https://github.com/OfficeDev/Office-Addin-TaskPane-React
2. update typescript
3. run eslint

--------------
Would it be possible support any new typescript version if something different from `@typescript-eslint/experimental-utils` was used?

**Comment by millerds** [comment]
Checked in a fix for this.
