### ISSUE TITLE
eslint-plugin-office-addins false positive

### ISSUE THREAD

**Issue by parched** [OfficeDev/Office-Addin-Scripts#671]
According to the [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model#ornullobject-methods-and-properties), the `isNullObject` property is loaded automatically, so there is no need for an error.

# Expected behavior

No warning

# Current behavior
> An explicit load call on 'spillParent' for property 'isNullObject' needs to be made before the property can be read.eslint[office-addins/load-object-before-read](https://docs.microsoft.com/office/dev/add-ins/develop/application-specific-api-model#load)

## Steps to Reproduce

```
const first = range.getCell(0, 0);
const spillParent = first.getSpillParentOrNullObject();
await context.sync();
const cell = spillParent.isNullObject ? first : spillParent; // error is on this line
```

## Context

`eslint-plugin-office-addins` version: 2.1.1

**Comment by millerds** [comment]
Thanks for pointing this out.  We'll add this to out bug backlog.

**Comment by millerds** [comment]
I believe this change should be published now.
