### ISSUE TITLE
Custom-Functions-Metadata for multiple files?

### ISSUE THREAD

**Issue by parched** [OfficeDev/Office-Addin-Scripts#681]
It would be useful if multiple files could be provided as the input to generate one output metadata JSON.
There's two reasons I've come across why this would be useful
* To modularize the code a bit more. E.g., we have hundreds of functions and it gets a bit unruly having them all in one file.
* Functions coming from different places do not need to be combined in a separate step. E.g., we have some functions that generated by a script and some that a hand written, currently, an extra step is needed to merge them for the metadata generator.

Personally, I'm only worried about Webpack plugin, not the command line tool.

**Comment by akrantz** [comment]
The json generation should work if multiple files contain @customfunction in jsdoc comment.  You just need webpack config to include them in the functions.js bundle. Easiest way may be to import into functions.ts

**Comment by parched** [comment]
@akrantz 
Do you mean like
```
    plugins: [
      new CustomFunctionsMetadataPlugin({
        output: 'functions.json',
        input: './src/functions/a.ts',
      }),
      new CustomFunctionsMetadataPlugin({
        output: 'functions.json',
        input: './src/functions/b.ts',
      }),
```
or
```
    plugins: [
      new CustomFunctionsMetadataPlugin({
        output: 'functions.json',
        input: ['./src/functions/a.ts', './src/functions/b.ts],
      }),
```
or something else?

The first only includes the second set of functions, the second throws an exception. The second is how I would like it to work.

**Comment by jacke-holmes** [comment]
I agree that I like the second option above, i.e. passing in a list of function files. This would then be consistent with how we pass the files to the entry: functions
![image](https://user-images.githubusercontent.com/100411377/189593624-accc252b-30bd-4f7d-8fb8-31577b72ef2f.png)

**Comment by jacke-holmes** [comment]
Also worth noting, multiple function files are being successfully added to the **functions.js** file. But it is the **functions.json** file that is not being correctly dealt with. We end up getting one .json file for every custom function .js file we create. This is the file the Manifest metadata refers to and it can only be one file currently.

**Comment by akrantz** [comment]
I meant the second way. You only want one instance of the custom functions plugin, but it should be able to scan multiple files for functions tagged as @customfunction.

I'm not actively working in this area now, but I know that I wanted to make sure it was possible to have custom functions in more than one source file. There were some changes with webpack, so maybe this was broken. 

You might first try the approach to have just "./src/functions/functions.ts" in the list. Try to create an exported function in in a second file, and then import into functions.ts.

file: functions2.ts

/**
@customfunction
*/ 
export function doSomething()
{
}


file: functions.ts

import { doSomething } from "functions2";

**Comment by jacke-holmes** [comment]
@akrantz
This doesn't seem to work if you only have "./src/functions/functions.ts" in the list. Also it's not really a scalable solution as we may have many custom function files. Also TypeScript complains if you import the file and then don't use it :).

From what I could see, if this were to work, it is likely it would only bring "doSomething" into the "functions.js" file. But we also need it in the "functions.json" file as this is the file that exposes the function to Excel

**Comment by millerds** [comment]
This looks like an improvement to the CustomeFunctionsMetadataPlugin is neeeded to:

1. Allow for an array as the "input" value (currently only string is allowed) and process the list of files
2. Merge the json output like the js output is doing

I don't think there is a good way to make this work in webpack config as it stands.

**Comment by millerds** [comment]
Support has been added for multiple function files in the lasted version of the plugin
