### ISSUE TITLE
Feature request: support .svg as Icon for Add-Ins

### ISSUE THREAD

**Issue by Sayan751** [OfficeDev/Office-Addin-Scripts#685]
Currently, the svg Icons, when used as both normal and high resolution Icons for O365 Add-Ins, work in browser. However, the validation infra does not validate the svg icons in the manifest.xml. 

```shell
npx -y office-addin-manifest validate manifest.xml
```

It produces the following error:

```
Error #1: 
Unsupported High Resolution Icon URL File Extension: The manifest high resolution icon URL must have a valid image file extension. Please see https://aka.ms/oackhighresolutionicon for details.
  - Details: svg

Error #2: 
Unsupported Icon URL File Extension: The manifest icon URL must have a valid image file extension. Please see https://aka.ms/oackicon for details.
  - Details: svg

The manifest is not valid.
```

Please consider supporting the svg icons officially, so that we don't need to maintain the icons of different dimensions.

Additional note: The links in the error messages do not seem to redirect to proper Information.

**Comment by millerds** [comment]
Can you be more specific about what you are doing to validate that gives you the error?

**Comment by Sayan751** [comment]
@millerds Sorry for the incomplete description. I meant this:

```
npx -y office-addin-manifest validate manifest.xml
```

Also updated the original post. 

Moreover, as far as I have understood it, the actual validation is happening remotely, as can be seen here:

https://github.com/OfficeDev/Office-Addin-Scripts/blob/a686eb3727af027dfa1f4ef3cb8ab3e0df3f821a/packages/office-addin-manifest/src/validate.ts#L99

**Comment by millerds** [comment]
We track add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Sayan751** [comment]
I have opened the feature request [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/support-svg-as-icon-for-add-ins/idi-p/3797009#M1703). Please feel free to upvote.
