### ISSUE TITLE
Some scripts reference to a malicious package "child_process"

### ISSUE THREAD

**Issue by DominikPalo** [OfficeDev/Office-Addin-Scripts#688]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

There is an NPM package called "child_process" which is marked as [a malicious package by Snyk](https://snyk.io/advisor/npm-package/child_process) and also [the NPM listing](https://www.npmjs.com/package/child_process) points to https://github.com/npm/security-holder

I've just found that this package is used/installed by the following Office Addin packages/scripts:

```
./packages/office-addin-node-debugger/package.json:25:    "child_process": "^1.0.2",
./packages/office-addin-debugging/package.json:26:    "child_process": "^1.0.2",
./packages/office-addin-dev-certs/package.json:35:    "child_process": "^1.0.2",
./packages/office-addin-dev-settings/package.json:27:    "child_process": "^1.0.2",
```

I'm not sure how those packages can even work without fulfilling that external "child_process" dependency, but there is a stable implementation of similar functionality directly in Node.js: https://nodejs.org/api/child_process.html - so maybe it's time to migrate to that internal Node.js implementation?

**Comment by millerds** [comment]
Thanks for pointing this out . . . we'll make the change.

**Comment by millerds** [comment]
This should be fixed
