### ISSUE TITLE
security issue: @microsoft/teamsfx-cli depends on adal-node which depends on xmldom version with security vulnerability

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/Office-Addin-Scripts#701]
see: https://github.com/Azure/ms-rest-nodeauth/issues/146#issuecomment-1280211322

**Comment by millerds** [comment]
Please report to teamsfx project: https://github.com/OfficeDev/TeamsFx

**Comment by JensMadsen** [comment]
@millerds are you not in the same company?

**Comment by JensMadsen** [comment]
https://github.com/OfficeDev/TeamsFx/issues/6485

**Comment by millerds** [comment]
We use a drop that has functionality that is not generally available yet.  Apparently, it doesn't include some updates to the packages that the main drop does.  I will have to follow up about getting those updates.  

Thanks for following up on this!

**Comment by millerds** [comment]
Updated package published now.
