### ISSUE TITLE
custom-functions-metadata-plugin@1.4.3 does not compile anymore

### ISSUE THREAD

**Issue by mm90849491** [OfficeDev/Office-Addin-Scripts#706]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [ y] I am running the latest version of Node and the tools
- [ y] I checked the documentation and found no answer
- [ y] I checked to make sure that this issue has not already been filed

# Expected behavior

Webpack should compile the project with custom-functions-metadata-plugin@1.4.3 without error

# Current behavior

Webpack failed to compile (see Failure Logs)
1.4.2 can be compiled without any error, I checked the repo's GIT history, "loader-utils": "^2.0.0" has been upgraded to v3, and it does not have getOptions export as the error complains.

## Steps to Reproduce

1. npm install custom-functions-metadata-plugin@1.4.3
2. npm build

## Context

* Operating System: Ubuntu 20, Windows 10, Ubuntu/Centos/Node Docker images
* Node version: v16.17.0
* Office version: doesn't matter
* Tool version: 1.4.3

## Failure Logs

```
Module build failed (from ../node_modules/custom-functions-metadata-plugin/lib/loader.js):
TypeError: (0 , loader_utils_1.getOptions) is not a function
```

**Comment by millerds** [comment]
Updated package publish that removed the loader-utils need per the major version update comments.
