### ISSUE TITLE
Cannot found the file `install.ps1`. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

### ISSUE THREAD

**Issue by woai3c** [OfficeDev/Office-Addin-Scripts#711]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Please describe the behavior you were expecting

# Current behavior

My system is windows11. When I run `npx office-addin-dev-certs install`. The program caused an error `\node_modules\office-addin-dev-certs\scripts\install.ps1` does not exisst. And I found that files `install.ps1` and `verify.ps1` have been deleted.

![image](https://user-images.githubusercontent.com/22117876/201527770-afe97faf-1a19-4d12-9ac0-87e0a89c76b5.png)

Before run `npx office-addin-dev-certs install`:

![image](https://user-images.githubusercontent.com/22117876/201528038-fa7d1f9a-d804-4c6c-84ee-ee1e2d3c1462.png)

After run `npx office-addin-dev-certs install`:

![image](https://user-images.githubusercontent.com/22117876/201528064-890fe04c-76bf-46f1-84c7-ee7ed690d5f5.png)

And then caused an error:
```shell
The developer certificates have been generated in C:\Users\Administrator\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate. The argument 'D:\res\office-add-ins\node_modules\office-addin-dev-certs\scripts\install.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npm install -D office-addin-dev-certs`
2. `npx office-addin-dev-certs install`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows 11
* Node version: 16.18.0
* Office version: office 365
* Tool version: 1.9.3

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.
```shell
The developer certificates have been generated in C:\Users\Administrator\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate. The argument 'D:\res\office-add-ins\node_modules\office-addin-dev-certs\scripts\install.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```

**Comment by millerds** [comment]
I'm not able to reproduce this and there is nothing in the code that would be modifying anything on the file system other than the files in the .office-addin-dev-certs folder.  The process is checking for valid certificate files in that directory, deleting those if they are not valid, generating certificate files if needed, and then running (via command prompt) "powershell -ExecutionPolicy Bypass -File '<PathToPs1>' 'CurrentUser' <PathToCertFile>" to update the certificate store.

Seems like something in the environment might be interfering.  Are you able to run that last PowerShell command manually from a command window?

**Comment by woai3c** [comment]
> I'm not able to reproduce this and there is nothing in the code that would be modifying anything on the file system other than the files in the .office-addin-dev-certs folder. The process is checking for valid certificate files in that directory, deleting those if they are not valid, generating certificate files if needed, and then running (via command prompt) "powershell -ExecutionPolicy Bypass -File '' 'CurrentUser' " to update the certificate store.
> 
> Seems like something in the environment might be interfering. Are you able to run that last PowerShell command manually from a command window?

Hi, millerds. Thank you for your reply. I have returned to Windows 10. Now everything is normal.
