### ISSUE TITLE
Unable to install certificates on user only without admin access

### ISSUE THREAD

**Issue by lucamattiazzi** [OfficeDev/Office-Addin-Scripts#718]
# Expected behavior

Issue is with package `office-addin-dev-certs`

When I want to install SSL certificates only for my user on OSX I should not need to have admin access to my machine in order to do so.

# Current behavior

Even if the `use-machine` flag is set to `false`, as it is if it's not otherwise explicitly set, installing the certificates will happen at a system level and not on an user level, due to the flag not being used.
Since `sudo` is used even without `machine` being `true`, this will always happen.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. In a project with a valid `manifest.xml` run the command `office-addin-debugging start manifest.xml`
2. You will be asked for admin access

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS Monterey 12.6
* Node version: 18.9.1
* Office version: 16.67
* Tool version: 1.10.0

**Comment by millerds** [comment]
New published package should include the submitted fix.
