### ISSUE TITLE
"eslint-plugin-office-addins" is conflicted with "eslint-config-airbnb-typescript"

### ISSUE THREAD

**Issue by Emiya0306** [OfficeDev/Office-Addin-Scripts#780]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior
Eslint works well

# Current behavior
Eslint crashed~

```javascript
//
module.exports = {
  extends: [
    'react-app',
    'react-app/jest',
    'airbnb',
    'airbnb-typescript',
    'plugin:office-addins/recommended'
  ],
  plugins: [
    'header',
    'office-addins'
  ],
}
```

[Error - 17:47:00] Error: Plugin "@typescript-eslint" was conflicted between "packages/excel/.eslintrc.js » plugin:office-addins/recommended" and "packages/excel/.eslintrc.js » eslint-config-airbnb-typescript » /xxx/node_modules/eslint-config-airbnb-typescript/lib/shared.js".
    at mergePlugins (/xxx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:598:19)
    at createConfig (/xxx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:701:9)
    at ConfigArray.extractConfig (/xxx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:877:33)
    at CLIEngine.isPathIgnored (/xxx/node_modules/eslint/lib/cli-engine/cli-engine.js:990:18)
    at CLIEngine.executeOnText (/xxx/node_modules/eslint/lib/cli-engine/cli-engine.js:899:38)
    at ESLint.lintText (/xxx/node_modules/eslint/lib/eslint/eslint.js:592:23)
    at /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:24378
    at E (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:18748)
    at e.validate (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:24337)
    at /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:220926

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. install eslint-config-airbnb, eslint-config-airbnb-typescript and eslint-plugin-office-addins, you will get this error.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS 12.6.3
* Node version: 16.16.0
* Office version: -
* Tool version: "eslint-plugin-office-addins": "^2.1.5", "eslint-config-airbnb": "^19.0.4", "eslint-config-airbnb-typescript": "^17.0.0",

**Comment by ndeleuze** [comment]
@Emiya0306 What kind of project are you working with? (Project type? Host application? TypeScript or JavaScript?) Also do you get the above error when running npm install for each of the three dependencies above?

**Comment by Emiya0306** [comment]
Oh thanks, I get the root cause!

My old project has already install "@typescript-eslint@^5.5.0", and the version "5.33.0" is locked by yarn.lock file.
Then I install "eslint-plugin-office-addins". "eslint-plugin-office-addins" dependence "@typescript-eslint@^5.33.1", and install the version "5.62.0".

So that is the function `mergePlugins` of `/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:601:19` will accept both `@5.33.0` and `@5.62.0` of "@typescript-eslint". And it will cause problem.

So it is the yarn's problem, not "eslint-plugin-office-addins".

<img width="940" alt="image" src="https://github.com/OfficeDev/Office-Addin-Scripts/assets/12878132/17c1cda3-9bdd-4f61-b5c2-1ac867ed6223">
Pic 1 My yarn.lock file content of @typescript-eslint

It will cause node_modules has two @typescript-eslint, and mergePlugins will be crashed.

<img width="656" alt="image" src="https://github.com/OfficeDev/Office-Addin-Scripts/assets/12878132/9ea73b65-fefc-4e1b-9a81-eb0dd368712b">
Pic 2 Crash in here

<img width="1052" alt="image" src="https://github.com/OfficeDev/Office-Addin-Scripts/assets/12878132/620fc98a-75e8-4659-afa8-5033cdd6c858">
Pic 3

<img width="1053" alt="image" src="https://github.com/OfficeDev/Office-Addin-Scripts/assets/12878132/8d45c0d8-93d0-4be3-8dad-fa88d7d057d9">
Pic 4 The correct yarn.lock file content of @typescript-eslint
