### ISSUE TITLE
office-addin-lint with Vue

### ISSUE THREAD

**Issue by Flyingdot** [OfficeDev/Office-Addin-Scripts#782]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Linter works in Vue Projects with SFC (Single File Components)

# Current behavior
When linting a vue-component in SFC-syntax, it fails with errors like this:
```
  2:9  error  Parsing error: '>' expected
```

a typical SFC looks like this (MyComponent.vue):
```
<script setup lang="ts">
Word.run(async (context) => {
   // ...
})
</script>

<template>
    <h1>Hello Office</h1>
</template>
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npm i -D office-addin-lint check`
2. .eslint.cjs
```
/* eslint-env node */
require('@rushstack/eslint-patch/modern-module-resolution')

module.exports = {
    root: true,
    plugins: ['office-addins'],
    extends: [
        'plugin:vue/vue3-essential',
        'eslint:recommended',
        '@vue/eslint-config-typescript',
        '@vue/eslint-config-prettier/skip-formatting',
        'plugin:office-addins/recommended'
    ],
    parserOptions: {
        ecmaVersion: 'latest'
    }
}
```
3. `npm run lint`
```
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --ignore-path .gitignore",
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: macos
* Node version: 18.16.0
* Office version: 
* Tool version:     "office-addin-lint": "^2.2.5",

**Comment by millerds** [comment]
From what I understand about eslint and the eslint-plugin-vue pluging you may need to adjust your eslint config to support parsing the .vue files along with other types of script in it.  See: https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser and https://github.com/vuejs/vue-eslint-parser#parseroptionsparser

FYI . . . tecnically office-addin-lint is basically a cli for linting basic ts and js files with a default eslint config.  The actual rules for office.js are in eslint-plugin-office-addins (which is a dependency of office-addin-lint) which are built for typescript and javascript.

**Comment by millerds** [comment]
Please comment when you get new information.
