### ISSUE TITLE
why is the exception  ignored when executing  "certs verify" command?

### ISSUE THREAD

**Issue by Code-Agitator** [OfficeDev/Office-Addin-Scripts#828]
# Prerequisites

* I want to validate my SSL certificate, but I encountered an exception due to the unavailability of OpenSSL. 
* However, I keep receiving the error message 'You need to install certificates for trusted access to https://localhost/' 
* I traced the source script and found issues with my OpenSSL. 
* I discovered that the exception caused by the command is ignored in 'packages/office-addin-dev-certs/src/verify.ts:53'. 
* Why not consider output or throw an exception?

![image](https://github.com/OfficeDev/Office-Addin-Scripts/assets/65442016/a7c73d4a-eef0-4bd6-ad2d-c9d7800199c8)

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

# Current behavior

**Comment by millerds** [comment]
Per the comment in the code shown in the screen shot, in some cases (this has to work across different platforms) exceptions are thrown when the certificate is just not installed as opposed to an error when trying to check.  The message returned indicates the certificate needs to be installed which is correct in those exception cases.  

However, you bring up a valid point that an exception isn't always going to simply be a lack of the certificate being installed.  It would be nice to at least provide some output showing what was going on and possibly distinguish between a "missing cert" exception and something else.

Thanks for reporting this.  I have added a work item to our backlog (internal id 8677374), but we cannot provide and estimate for when we might get to this.  Feel free to submit a PR with a fix for our consideration if you don't feel like waiting.
