### ISSUE TITLE
office-addin-debugging Unsupported engine

### ISSUE THREAD

**Issue by andrewkittredge** [OfficeDev/Office-Addin-Scripts#830]
office-addin-debugging has a transitive dependency on @azure/msal-node@1.18.4 which does not support node v20.

**Comment by akrantz** [comment]
This is being worked on. Are you able to use Node v18 in the meantime?

**Comment by andrewkittredge** [comment]
Any progress on this?

**Comment by akrantz** [comment]
Edit the .npmrc file and remove `engines=strict`. Node v20 will work fine.

**Comment by millerds** [comment]
I also just published updates script packages that finally got the version of the dependency that has all the fixes in it.  It should be clean now with the latest office-addin-dev-settings (a dependency of office-adding-debugging).
