### ISSUE TITLE
validate works in CLI but office fails validation

### ISSUE THREAD

**Issue by sakgoyal** [OfficeDev/Office-Addin-Scripts#832]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Please describe the behavior you were expecting

# Current behavior

Tried to make a office add in and followed the docs, but I can't install it because the validation fails for some reason.

![image](https://github.com/OfficeDev/Office-Addin-Scripts/assets/19929553/deb182c4-4eed-43bb-8489-21e821c78431)
![image](https://github.com/OfficeDev/Office-Addin-Scripts/assets/19929553/86a57aa1-4b33-410b-a011-39036b1f1b31)

( I had to rename the file to txt, but this is the xml file )  
[manifest.txt](https://github.com/OfficeDev/Office-Addin-Scripts/files/14060886/manifest.txt)

**Comment by millerds** [comment]
What documentation did you follow?  That screenshot shows that you aren't using current/official tooling to validate the manifest office-toolbox repo was archived a few years ago (and isn't part of this repo) and isn't what been used in the projects generated by 'yo office' (which do come from this repo) for longer than that.

**Comment by sakgoyal** [comment]
I generated this with `yo office` and selected the manifest only option. 
I want to use my exiting Next.js website and add the `taskpane.html` and `commands.html` to it so I can use that instead of starting from scratch with react.

**Comment by millerds** [comment]
I understand now.  Looks like the manifest only project template is outdated (and doesn't follow the pattern of the other templates).  We'll have to fix that, but you can correct your project by modifying package.json and replacing the validate script with 'office-addin-manifest validate manifest.xml' and updating the dependency to use 'office-addin-manifest' instead of 'office-toolbox'.  Do that and run 'npm install' and then the validate command should be accurate.

**Comment by sakgoyal** [comment]
I did that just now and it still did not work. 

do the URLs have to be functioning before I can submit the xml?
I do not have the server running yet. I just want to make sure I know how to set up the xml in the first place.

**Comment by sakgoyal** [comment]
my package.json
```json
{
	"name": "xxx",
	"description": "",
	"author": "",
	"version": "0.1.0",
	"scripts": {
		"validate": "office-addin-manifest validate manifest.xml"
	},
	"dependencies": {
		"office-addin-manifest": "^1.12.9"
	},
	"devDependencies": {}
}
```
my manifest:
(ignore the ngrok URLs for now. thats just so I dont need to use "localhost")

```xml
<details>
<summary>Details</summary>

<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
          xsi:type="MailApp">

  <!-- IMPORTANT! Id must be unique for your add-in, if you reuse this manifest ensure that you change this id to a new GUID. -->
  <Id>88b25cde-69dd-4c4e-b146-47bce50e102d</Id>

  <!--Version. Updates from the store only get triggered if there is a version change. -->
  <Version>1.0.0.0</Version>
  <ProviderName>ConstructWorks AI, Inc.</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>

  <DisplayName DefaultValue="AttorneyAI" />
  <Description DefaultValue="[Outlook Add-in description]"/>

  <IconUrl DefaultValue="https://i.imgur.com/ZtyFMvT.png" />
  <HighResolutionIconUrl DefaultValue="https://i.imgur.com/tf8dZ8B.png"/>

  <SupportUrl DefaultValue="https://construct.works/help" />

  <AppDomains>
    <AppDomain>https://construct.works/</AppDomain>
  </AppDomains>

  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://69c6-65-222-240-195.ngrok-free.app/index.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Requirements>
      <bt:Sets DefaultMinVersion="1.3">
        <bt:Set Name="Mailbox" />
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">

        <DesktopFormFactor>
          <!-- Location of the Functions that UI-less buttons can trigger (ExecuteFunction Actions). -->
          <FunctionFile resid="Commands.Url" />

          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <!-- Use the default tab of the ExtensionPoint or create your own with <CustomTab id="myTab"> -->
            <OfficeTab id="TabDefault">
              <!-- Up to 6 Groups added per Tab -->
              <Group id="msgReadGroup">
                <Label resid="GroupLabel" />
                <!-- Launch the add-in : task pane button -->
                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                  <Label resid="TaskpaneButton.Label" />
                  <Supertip>
                    <Title resid="TaskpaneButton.Label" />
                    <Description resid="TaskpaneButton.Tooltip" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16" />
                    <bt:Image size="32" resid="Icon.32x32" />
                    <bt:Image size="80" resid="Icon.80x80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="Taskpane.Url" />
                  </Action>
                </Control>
                <!-- Go to http://aka.ms/ButtonCommands to learn how to add more Controls: ExecuteFunction and Menu -->
              </Group>
            </OfficeTab>
          </ExtensionPoint>
          <!-- Go to http://aka.ms/ExtensionPointsCommands to learn how to add more Extension Points: MessageRead, AppointmentOrganizer, AppointmentAttendee -->
        </DesktopFormFactor>
      </Host>
    </Hosts>

    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://i.imgur.com/hHzt8TD.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://i.imgur.com/fsKDVk8.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://i.imgur.com/RqI6OQW.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Commands.Url" DefaultValue="https://69c6-65-222-240-195.ngrok-free.app/commands.html" />
        <bt:Url id="Taskpane.Url" DefaultValue="https://69c6-65-222-240-195.ngrok-free.app/taskpane.html" />
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GroupLabel" DefaultValue="Contoso Add-in"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a pane displaying all available properties."/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
```


</details>

**Comment by millerds** [comment]
How are you installing the add-in?  The manifest says "Mailbox" add-in which is for Outlook . . . but your error message screenshot is asking for feedback for Word.

**Comment by sakgoyal** [comment]
Yea I was trying to use word because I can't find the same button in outlook. ( I am using the 365 developer pack account). ive looked for an hour and I see no way for me to add the plugin through outlook

**Comment by millerds** [comment]
Word is going to reject the add-in because it's intended for Outlook.  Outlook is in the middle of changing the add-in entry points and the sideloading option is somewhat hidden.  If you go to File -> Manage Add-ins the browser will open with the older experience.  Click on "My add-ins", scroll down and click the "Add a custom add-in" link.  This should let you load the manifest and it should show up in the rich client when you reboot it.

**Comment by sakgoyal** [comment]
ohhh. that was very fraustrating, but Im happy it works now!

Also, I know its not in the scope of this repo, but do you know how I can use next.js instead of react? I didnt find any resources describing how to use Next instead of React. (Next.js is a framework built on top of react, but its quite different in terms how to how use it)

**Comment by millerds** [comment]
Not familiar with that.  As far as office add-ins go it shouldn't really be different (manifest and office.js calls) . . . it would just be general framework differences.
