### ISSUE TITLE
custom-function-metadata should not use fs in parseTree

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/Office-Addin-Scripts#837]
# Expected behavior

parseTree should be exported independently without references to `fs`.

i.e. there should be a file called `parseTree.ts` that only includes parseTree code and does not include `generateCustomFunctionMetadata`

**Comment by akrantz** [comment]
I think what is needed here is to rename generate.ts to parseTree.ts, and then move generateCustomFunctionsMetadata() to a new generate.ts file. Then main.ts can export from both generate.ts and parseTree.ts.

**Comment by millerds** [comment]
Isn't this the main part of what @wandyezj existing PR is trying to do or am I missing something?

**Comment by wandyezj** [comment]
This was fixed by @akrantz
