### ISSUE TITLE
packages should specific exactly what they export.

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/Office-Addin-Scripts#838]
All packages should be clear about the specific types they export in their top-level index file.

This makes it easy to tell what types a package is intended to export.

This also helps prevent export of internal types.

This makes it easy to tell what is added / removed / changed between package versions by looking at the top level file.

This also prevents regressions where types are unintentionally renamed or moved.

**Comment by millerds** [comment]
We discussed this in our triage and it looks like a reasonable common practice.  It would be nice to reference a specific industry standard to this effect.

However, this is low priority for us to do ourselves.  We would consider a PR done by someone else that updates all the packages in this repo in the same way.
