### ISSUE TITLE
Issues with AppContainer Loopback Logic in `office-addin-debugging` and `office-addin-dev-settings`

### ISSUE THREAD

**Issue by ZYUN-MSFT** [OfficeDev/Office-Addin-Scripts#840]
Hi all, I recently found some issues/strange behavior with the loopback logic.

# Background

I know that AppContainer tech make some Apps likes UWP can't access localhost (loopback) by default.
In previously, I think Webview2 && Edge need that loopback exempt for Add-in side-load.
But some test I did recently shows that things may be different.

**Tools I used：**

* AppContainer Loopback Exemption Utility, which is build in with Fiddler Classic.
* `CheckNetIsolation.exe`

# Issue 1: Type `No` during Loopback question prompt

* OS: Win11 23H2

[Code](https://github.com/OfficeDev/Office-Addin-Scripts/blob/046cf733ee7291e33bc973d912592242932a8e0c/packages/office-addin-debugging/src/start.ts#L309) in `office-addin-debugging` dosen't use the result from [`ensureLoopbackIsEnabled`](https://github.com/OfficeDev/Office-Addin-Scripts/blob/046cf733ee7291e33bc973d912592242932a8e0c/packages/office-addin-dev-settings/src/appcontainer.ts#L125):

```ts
// enable loopback for Edge
if (isWindowsPlatform && parseInt(os.release(), 10) === 10) {
  const name = isDesktopAppType ? "EdgeWebView" : "EdgeWebBrowser";
  await devSettings.ensureLoopbackIsEnabled(name);
}
```

```ts
export async function ensureLoopbackIsEnabled(
  manifestPath: string,
  askForConfirmation: boolean = true
): Promise<boolean> {
  const name = await getAppcontainerNameFromManifestPath(manifestPath);
  let isEnabled = await isLoopbackExemptionForAppcontainer(name);

  if (!isEnabled) {
    if (!askForConfirmation || (await getUserConfirmation(getDisplayNameFromManifestPath(manifestPath)))) {
      await addLoopbackExemptionForAppcontainer(name);
      isEnabled = true;
    }
  }

  return isEnabled;  // if user type No, this will return false
}
```

**So, when `ensureLoopbackIsEnabled` detect that loopback is not exempted and user type `No`, the logic in `office-addin-debugging` will carried on the following steps (start the dev server and side load the add-in).**

**_Then the things get interested:_**
1. I first delete all loopback exempt
  ![No Loopback exempt](https://github.com/OfficeDev/Office-Addin-Scripts/assets/122421505/2c7980e6-3551-4c70-ad96-c2e50ba936e6)
2. Then I try start debug in add-in project and type `No` during loopback question asked
3. **I found that add-in side load successfully even without Edge/Webview2 loopback exempt.**
  ![result](https://github.com/OfficeDev/Office-Addin-Scripts/assets/122421505/8161f19d-f68d-4bed-9198-59e93bef18ce)
4. I also try to start in web, the result is the same
  ![result-web](https://github.com/OfficeDev/Office-Addin-Scripts/assets/122421505/d944568d-68b1-4706-aa6a-a1d35ceaa1ac)

**_These result shows that maybe the Loopback exempt is no needed for user to side load the add-in._**

# Issue 2: Edge App Container Name

In this [code file](https://github.com/OfficeDev/Office-Addin-Scripts/blob/046cf733ee7291e33bc973d912592242932a8e0c/packages/office-addin-dev-settings/src/appcontainer.ts#L12), we can see the Edge Browser App Container Name (AC Name):
```ts
export const EdgeBrowserAppcontainerName: string = "Microsoft.MicrosoftEdge_8wekyb3d8bbwe";
export const EdgeWebViewAppcontainerName: string = "Microsoft.win32webviewhost_cw5n1h2txyewy";
```

However, on **my new Win11 23H2 machine, I don't have Edge that with AC Name, instead I have a Edge with AC Name of `Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe`**:

![ac name1](https://github.com/OfficeDev/Office-Addin-Scripts/assets/122421505/b932d427-a2a5-49e5-a47b-c2b725731954)

But in my two other machine (one is Win11 which upgrade from Win10, another is Win10), **they both have two Edge App Container** and one is `Microsoft.MicrosoftEdge_8wekyb3d8bbwe` another is `Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe`

![Win10 ac name](https://github.com/OfficeDev/Office-Addin-Scripts/assets/122421505/d6bda4c2-296a-468a-81a7-b9a56190b668)

![Win10-Win11 ac name](https://github.com/OfficeDev/Office-Addin-Scripts/assets/122421505/809849d6-60c0-4891-8d9a-7e1e54916b6f)

# Issue 3: The way to check whether Edge Browser have Loopback exempt maybe wrong

This [code](https://github.com/OfficeDev/Office-Addin-Scripts/blob/046cf733ee7291e33bc973d912592242932a8e0c/packages/office-addin-dev-settings/src/appcontainer.ts#L53) shows that how to check the app have the exempt:

```ts
export function isLoopbackExemptionForAppcontainer(name: string): Promise<boolean> {
  if (!isAppcontainerSupported()) {
    throw new ExpectedError(`Platform not supported: ${process.platform}.`);
  }

  return new Promise((resolve, reject) => {
    const command = `CheckNetIsolation.exe LoopbackExempt -s`;

    childProcess.exec(command, (error, stdout) => {
      if (error) {
        reject(stdout);
      } else {
        const expr = new RegExp(`Name: ${name}`, "i");
        const found: boolean = expr.test(stdout);
        resolve(found);
      }
    });
  });
}
```

But I did some test here:

![test](https://github.com/OfficeDev/Office-Addin-Scripts/assets/122421505/ae7cbf39-48f8-48b9-98cb-a506724f253f)

**_We can see that for `EdgeWebViewAppcontainerName`, this way works. But for `EdgeBrowserAppcontainerName` this way not work._** Though `Microsoft.MicrosoftEdge_8wekyb3d8bbwe` already have exempt but `.\CheckNetIsolation.exe LoopbackExempt -s` will not list it.

# Issue 4: Only Add Edge Browser to loopback Exempt maybe not correct.

When sideload in web, this [code](https://github.com/OfficeDev/Office-Addin-Scripts/blob/046cf733ee7291e33bc973d912592242932a8e0c/packages/office-addin-dev-settings/src/sideload.ts#L388) show that `open` is used for open the sideload link. 

```ts
async function launchApp(app: OfficeApp, sideloadFile: string) {
  console.log(`Launching ${app} via ${sideloadFile}`);
  if (sideloadFile) {
    if (app === OfficeApp.Outlook) {
      // put the Outlook.exe path in quotes if it contains spaces
      if (sideloadFile.indexOf(" ") >= 0) {
        sideloadFile = `"${sideloadFile}"`;
      }

      startDetachedProcess(sideloadFile);
    } else {
      await open(sideloadFile, { wait: false });
    }
  }
}
```

**But [`open`](https://github.com/sindresorhus/open) seems to open link with system default browser, which may not be Edge.**

So only exempt Edge Browser maybe not correct. But accroding to above information, maybe exempt browser is not needed.

**Comment by hermanwenhe** [comment]
More thoughts on this:

Since the `CheckIsolation` logic is added 5 years ago and we do find out this logic is not needed on Windows 11. Maybe we should re-check this and find out is this check a required step? Maybe we can remove this check for certain OS version or we can set the default value to "NO" to avoid the "Access Denied" issue.

Add @millerds @akrantz for discussion.

**Comment by akrantz** [comment]
I'm not working in this space now, so Darren can investigate. It may be that the webview2 code allows the localhost loopback when debugging or this was allowed in a mechanism which CheckNetIsolation doesn't report. Certainly there are different flavors and ways of installing webview2, as you mention the different app ids.

**Comment by ZYUN-MSFT** [comment]
I make a [PR](https://github.com/OfficeDev/Office-Addin-Scripts/pull/847) with simple change to keep behavior the same when user type `Yes` or `No` when asking loopback question.

---

Some other investigation I found:

I found the following docs:
* [Manually sideload an add-in to Office on the web](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#manually-sideload-an-add-in-to-office-on-the-web)
* [Start the Excel, PowerPoint, or Word add-in project](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/debug-office-add-ins-in-visual-studio#start-the-excel-powerpoint-or-word-add-in-project)
* [Can't open add-in from localhost: Use a local loopback exemption](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting#cant-open-add-in-from-localhost-use-a-local-loopback-exemption)
* [When the add-in tries to open, get "ADD-IN ERROR We can't open this add-in from the localhost" error](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#when-the-add-in-tries-to-open-get-add-in-error-we-cant-open-this-add-in-from-the-localhost-error)

**_In the first doc, it said that for Legacy Edge, it need the loopback exemption, but for Webview 2 it doesn't need so._**

Maybe this is the kernel cause of all my above issues.

**Comment by Adrian-MSFT** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term due to the amount of effort needed for this and the fact that the PR you created provides a workaround for this as well. If we end up working on this issue we will re-activate as needed.
