### ISSUE TITLE
"Unable to start the dev server" on Ubuntu WSL

### ISSUE THREAD

**Issue by videate-carlos** [OfficeDev/Office-Addin-Scripts#852]
# Expected behavior
`npm run start:web [URL]` starts the dev-server, opens the Document and loads add-in

# Current behavior
`npm run start:web [URL]` fails:
```
> office-addin-taskpane-react-js@0.0.1 start:web
> office-addin-debugging start manifest.xml web [URL]

Debugging is being started...
App type: web
Starting the dev server... (webpack serve --mode development)
Unable to start the dev server. Error: The dev server is not running on port 3000.
Sideloading the Office Add-in...
Error: Unable to start debugging.
...
```

## Steps to Reproduce
1. `yo office --projectType react --name "New Web AddIn" --host word --js` 
2. `cd New Web AddIn`
3. `npm start:web [URL]`

## Context
* Operating System: Ubuntu 22.04.3 **LTS** via WSL
* Node version: v18.20.2
* Office version: Web?
* Tool version:

I initially ran into this issue when trying to tun a project repo which  uses `office-sddin-scripts`, specifically it has a `script` that runs `office-addin-debugging start office-addin/manifest.xml --dev-server='npm run start:office:server' web --document`. This works fine on Linux and macOS but this time I was trying to run it on Ubuntu under WSL. I recreated a new project using the _yo generator_ and it was still not working.

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.
```
> office-addin-taskpane-react-js@0.0.1 start:web
> office-addin-debugging start manifest.xml web [URL]

Debugging is being started...
App type: web
Starting the dev server... (webpack serve --mode development)
Unable to start the dev server. Error: The dev server is not running on port 3000.
Sideloading the Office Add-in...
Error: Unable to start debugging.
```

**Comment by zhngx1** [comment]
Is the issue only when you are trying to run the Office Web? The issue is also only happening on Ubuntu, not other platforms?
From the log it looks like something is running on port 3000, can you try to look what process is running on port 3000?

**Comment by zhngx1** [comment]
Please reopen the issue if you still run into this issue.
