### ISSUE TITLE
office-addin-sso needs to be updated to work with the JSON manifest

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Office-Addin-Scripts#853]
## Context

The SSO project templates can now support the JSON manifest, but the office-addin-sso tool has to be updated to edit the JSON manifest just as it edits the XML manifest. E.g., replace "{PORT}' with the port number.

**Comment by Rick-Kirkham** [comment]
@millerds Would it be possible to get this issue done by, say, end of August?

**Comment by millerds** [comment]
Change was needed in the template repo instead of the script repo.  Change is checked in . . . it just needs to be published to the release branch (yo-office)
