### ISSUE TITLE
excel-custom-functions-js Unsupported engine (node 20)

### ISSUE THREAD

**Issue by stefandrissen** [OfficeDev/Office-Addin-Scripts#860]
New to node and npm, just want to create an Office Add-in, using current node LTS- running into warnings:

````
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'excel-custom-functions-js@0.0.1',
npm WARN EBADENGINE   required: { node: '>=16 <19', npm: '>=7 <11' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
````

Caused by:

https://github.com/OfficeDev/Office-Addin-Scripts/blob/69273a7a8c73c525704cd5d52e1a901475d291cd/packages/office-addin-project/test/package.json#L15

Also:
````
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
````
But that has already been identified in https://github.com/OfficeDev/Office-Addin-Scripts/issues/830

**Comment by akrantz** [comment]
The warning can be ignored. We've are working to get dependent packages to be updated so there is no warning.
