### ISSUE TITLE
office-addin-lint --files option not working when passing multiple file paths

### ISSUE THREAD

**Issue by Luminqi** [OfficeDev/Office-Addin-Scripts#906]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

I am using husky and lint-staged with office-addin-lint to do pre-commit lint. I want to pass multiple staged files to --files option, that I expected lint and prettier will process all the staged files.

```javascript
module.exports = {
  'src/**/*.{ts,tsx,js,jsx}': (stagedFiles) => [
    `office-addin-lint fix --files ${stagedFiles.join(' ')}`,
    `office-addin-lint prettier --files ${stagedFiles.join(' ')}`
  ],
}
```

# Current behavior

Only the first staged file is being lint and pretter.

**Comment by millerds** [comment]
The "--files" argument takes in a string and the spaces between your file list terminates the string and make it look for the next cli argument.  You should instead provide the "src/**/*.{ts,tsx,js,jsx}" directly to the command (which is actually the default value if you didn't specify anything).  If you don't want to do that, put the list of files in quotes ("${stagedFiles.join(' ')}") so it's read as a single value for the switch argument.
