### ISSUE TITLE
@customEnum JSDoc tag

### ISSUE THREAD

**Issue by adim1973** [OfficeDev/Office-Addin-Scripts#912]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

I'm trying to use the @customEnum JSDoc tag for a custom function, following the example from here: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/custom-functions-metadata/test/cases/enum/functions.ts.
Citing from these specs: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages%2Fcustom-functions-metadata%2FSpecification.md: "**When a custom function uses this custom enum as the type for its arguments, the enum values will be displayed in a dropdown list for the end user when they enter the function**"

# Current behavior

I'm using the exact functions.json like in the correlated example: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/custom-functions-metadata/test/cases/enum/expected.json, but no dropdown is shown.

## Steps to Reproduce

Create a starter Excel add-in.
Add the sample custom function from here: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/custom-functions-metadata/test/cases/enum/functions.ts
Generate the functions.json like in this example: https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/custom-functions-metadata/test/cases/enum/expected.json

**Comment by akrantz** [comment]
Sorry, but you cannot use this right now. This is part of a potential improvement for custom functions which is under active development. We cannot guarantee whether this would actually be released, or what the time frame might be.
